ώZUUZώWUWWWWWZώUXXWUXUX[WWUώUWZUXUXWWXZU[WZZώVUW[WVZσ[Z[ZWWWZώ
ZZWZZZXστZZXWXWZUZUώZZZZVWUWπτφττφχZXZUWUZZWώWZZVZWUWWZπσωσςστχψZWWUWZVZZWώWZZUWUZπυϊτψχψχττυϊχUWVZZZZώUZUZWωψϋυωωωϊυχωϋψZWZZώ
ZWWWZφϊωϊόϊωψ
ϋWUVώZZW[XUXWWϋϊωWUώUWW[UXXUWXXUώZWWWWWUWώZUUZÿώφωώψ	ωώψ	ψώώψτχώσσσ	ώττφώZ
τχώσσσσ	ώ	χτ	φώψώψχωω	τ	
σσσώχτ	φUωωωψ
	σώφχτ	φχ			ωψχψώ
τωχτ	ψττ

ωφφχχώ
	
χχχτφχψ	ττφψχχωώZσσ	χφφτττχωχφχχτ	ωφφψωφώWZZ
ψωωχ	ςςωψψω
ψωφψφφVZZWώWZZUWUψτψ
ςςτφτσ
ψφωωψZZώUZUZWXWωφτωσσσσ	υWZZώ
ZWWWZ\τω	σφρσωWUVώZZXZφω
σσσφωWUώUωωωωψψψωXXUώZWWWWWUWώZUUZÿώZUUZώWUWWWWWZώUXXWUττυ[WWUώUWZUςςφWZZώVUW[ςςWWWZώ
ZZWZZ²³συZUZUώZZZZVτσ΄³²²τσςψχUZZWώWZZVZWU	χυσς΄µ΄΄ςτυτσωϊωWZVZZWώWZZUW	ωφτυσµ·¶··σφϊωϋZZZZώUZUZϊχχψφωΉΈ¶¶ψωόϊωWZZώ
ZWWωωϊυψϊφΉΉψωϊόϋUVώZZW[XϊχψΉωϊϋZWUώUWW[			UώZWWWWWUWώZUUZÿώυσσσσσσσσσσσσώυτσττττττυυττττώττσστττυυχστττττώυτυυσστττσστττττττώτυυσσττττυυυσστττώυτ
υυσστττυψσστττττώτυ

υυτστττσστττυτττώ	υτυυ	υστστττττυυχστττώυυυ	
υυφφφφφφφυυυφφφώτυυυυυ
φφυφφώυτυυυυυ	φχχχχχχχχχφώτ

υυυυφχφχχχχχχφώυτυυυυχφχχχχχψχφώτυυυ		υφφφχψφχψωψφώτυυυ
υ	φχχψχψωωωφώυ	υυυυυ
υφχχωψωχωZZ[φώς
υυυυυυφψωωχωωψXXZ[ώZZZZυ
υυυυφψχZψZψω[XVXZZWώWZZVZWUυ	VXυφZZXZV[ZZWUWZVZZWώWZZUWUXVUυφφZVWVXXZWUWVZZZZώUZUZWXUVUφZXWXZZWXZZZWZZώ
ZWWWVVVXXZZXXZVW[WUVώZZWVXUXWWXUXUZWUώUWW[UXXUWXXUώZWWWWWUWώZUUZÿώµΆ£[ώ[£Ά΅]][£΅£Y£ώ£΅£[]]£££\[][]Yώ^][[ZY£΅[΅Ά\\ZZ[Άώ£YZZZ£΅΅΅££[[ZYµ£^ώY]][ZYYYYY[[[Z£Ά^]]ώ^Ά[ZΆ£[ZZZ[ZΆµ΅Y[\\ώ^£µ£΅µΆZ[΅ΆY\^\[[[ώ]\][][£µµ]]\[Z[[[\ώ\[[£Ά΅[]]£ZZΆZ[[[[ώ[[Z££΅ΆYΆYZZ£Z[[[Zώ\[ZY£΅Ά£Ά£YZZYZ[ΆZ]ώ[[ZY£΅΅££΅££YYZY\^]ώZZZ[ΆYΆ££΅£Y£ΆΆ[[\\ώ]£µΆµ΅Ά££΅ΆY\^^[[[ώV]]Z[]Y΅µµ]]\[Z[[[\Zώ
ZZW\[[YYZ[]]ZZZZZ[[[ZUZUώZZZZV[[Z£££ΆYZYZZXWX[ZUWUZZWώWZZVZWU\[Z£££΅£££YXWUWXXWUWZVZZWώWZZUWU[ZY££΅£££WSUSUWUWVZZZZώUZUZWWZYY£ΆYXWUTSUWWZWZZώ
ZWWWZYXWWWWUWUUWUWUVώZZW[XUXYWWUWWUWUώUWW[UXXUWXXUώZWWWWWUWώZUUZÿώώ
ώ

yώ			
y
ώ

	
	
ώ		
			
ώ
	

	
;ώ
		


ώ

φ	
χ<=ώ




χψω=ώψωωώ
ώ
	
ώ
		

ώ

φ	
ώ	




ώ

ώVU		Zώ
ZZWZ
	UZUώZZZZVW
		

WUZZWώWZZVZWUW

φ	
UWZVZZWώWZZUWUZ




WVZZZZώUZUZWYZ[ZWZZώ
ZWWWY[[WUVώZZW[WUώUWW[XXUώZWWWWWUWώZUUZÿώώόώόώόό
όώόW
όόUώόXUXόόWZZώVόόZZZ
όόZWWWZώ
[ZWόό[\[	όόWXWZUZUώZZZZVWUZό\\\	όXZXZUWUZZWώWZZVZWUWWXόό]^^
XW[ZWWUWZVZZWώWZZUWUZπ\\\\XZXZ[UWVZZZZώUZUZW[[\Z[ωZ[\[ZZZWZZώ
ZWWWZZZZZ[\ZZ\\WUVώZZW[XUXWWZZ\WUώUWW[UXXUWXXUώZWWWWWUWώZUUZÿώώ
ώ
ώ	

ώ

ϊϊ
ώ
		
ό
ώ
		

ό
ώ

σρρρ	
όόώ





όόώ	όόόώ

όόόώ
	ώόόόόόόώ
		

όό
όόώ	


σρρρ	
ό
όώ







ό
ό
ώ

όόόώ
σόόό
ώόόώ
σόόόόό
ώόώ
	όό

όό
όώόώρ




όώόώρ

σ
	
όώόώρ
σ
όόόώόώ
	
όόόώ	ό
ρόόόόώ
ό
ρόό
όώωό
ρό	
όώό
όόόώ

όό	όόόώWZZόόό
όόόZWώWZZόόόόόόόωόόόZZώUZUZ
όόόόZZώ
ZWWόόό

WUVώZZWόόόόόWUώUWW[UXXUWXXUώZWWWWWUWώZUUZÿώ]VVXώ[V[XX[[VώV]\ZZZ[]]]]XώV[Z[\\\\]]]][WX[ώWV[Z\\]]]]]^]]\[]]XWώ
]]X][\]]]]]^^^^]]]\\ZZVXώZZ][[[]]]^^^^^^^^^^]][ZX[[]§ώX]]WZ[[\]]^________^^]]\ZZ\\]]]]ώ[ZZV[[]^^_______^^^]]\[[ZZWXώV]VZ\]^_____^]]]]]\[ZZXVώ
]X\\]]^^^^]]\\\[\ZZXώ]Z[\]]]]\[ZZYZYXώV[]]\[ZZXXXYώ]][YV\[Xώ]VVXÿώ\UU\ώ[UZYYZZ[ώUXW\WWWW[WZUώUZYWW[XWWWYU[ZY\ώVU\]\X\XWYZX[^[YZZW\ώ
\\YYW\XW\\YY\Y^^W\ZYUU\UώYY\\XYWZW\YX[Y]Y^^WVZ^UWUYYZώW\\VYZWYYYXWYZYYY[ZWWVYYYU\YV\\WWVZYYUYW\ZXW^ZYXXYYY\WZWYX^^YYVVTWZZU\WWYZZY[\Y\\[[\WX\W[W^^WVVVVW]WWU\WZZZY\[XYYZZWVZ[ZUVZXWWY[UUT]WWVV\[W]WWXWWZUUWYZUZZZZ[[[]VVU[[YYXTUUZZ]WWWWZXXZX\\\[YYY[WWXVVVTWZZWWW\ZZWWZUZZZ\\\[ZXYW[[W[YYVVYZZU]YWU\UU\ZZ[[\\[WSXVV[[UWWTVVZT[VYYY\XXZZ[[\\[\X\VV[[YZώUWWTVVZZ[VYY[W[[VWXX][\Z[[ZZώWW\]Z[ZV[VXW[\WWX\[\\\ZZώ
UTZWXWVUZYV[YX[[\\\XώVVWWZVUUV[[[ZZZZώUWWWWVXYWWXZώWVWTVVVWώVWVVÿώ\]X\ώ^][ZYY[\ώ^]Z]XZX[]YYWώ]Y\ZZ^]\[]\]]Y\]ώXWY]YX\Z]YXZ]\]]YY[\ώ
]]Y\[\ZY[[YXY[\\ZYZ[\W\]ώ\]\]^]WYY[^][]\Y[\W\Z\WVZ[\]ώY]\XZYWXY\XWY[Y\ZWZY\]]^\WY]XY[][VY\\WYY[ZYZ\]]^]YZ]\Y[\]X[]Z[ZZ\W[\W\X[Y[Z[]\[\Y\[\YZ\]\YZ[WZZZ\\W][[\YZ[[][]Z[\[Z[X]^YWXZX]\^XU\TTW\Y^\\Y]ZXZYYZ[]]^YWZZZZ[[[VVV\WWXWXTUWYY]XZZ[YZZX[]]\[[]V[VW[^]\]XZZVWW\[ZYYZWYZZ]X^[Y]VW[[[[Y\^^\]VVTWW\\XW\ZZ[[\]W\]VVZZ\\\\[[UW\WVTWWYYY\[\[\VZWY[VVZ[]\XUU\UYX\ZVTUWWWYZZWZVZ\]Y^XZZ\\\]V\\U[\[\TTTUYUY\ZV^Z\YWVY][Z\\[WXUUU[\W]TTUTY[[VVZ^\]Y]Y[^]]\\Z[XZT]\Z\\TUYYU\]UW]]]V\TW\]]]\XYWXXU\WV[[YUU[ZUUY[]V[TY\\Y\]VXXXWXT\X[U[\]\\UU[[XY^^WX^\Y[V]XXYTZT[\[[Y^]UZUXYZ[\UYY]\\^]Y^XYXTT]]T[[\XTTT]ZXWXVUX]XYWYYVY\ZWX[Y[TY[]YW]\Y\^YY[VY[]\[YVWZY[ZY[[TTTU\[YY][[YWXYXVV][[Y[WW^\U[[^ZTVTTWWX[U[UXXWYYVV[YVVXW\Z[\UUY^TTTU\[]XY]TZXZYXVV]VWVX\^Y[^WWX\\YYXX\]XY\U]\W\\XV]\WW[YWZZW\^YXWWTTTW\YXUT[VW[ZWV]ZXW[^ZW[Y]YYWWYYT[U^Y\X\[UXX[^ZZXVWTXVWZ\[^YVWWVT\UZUY]\[\\X[VVVXY]\\\\[[[\ώUWWTV[\TYVYX[W[WVV^X\[ϋ\[[ZZώ]^V\[W\VVVX][WW]XY]\\\ZZώ
UTZWWW[YVVVXYY[\\\\XώVV[WTTUUV[[[ZZZZώUWWWWVXYWWXZώWVWTVVVWώVWVVÿ	ώ\UU\ώ[UZYYZZ[ώUXW\WWWW[WZUώUZYWW[XWWWYU[ZY\ώVU\]\X\XWYZX[^[YZZW\ώ
\\YYW\XW\\YY\Y^^W\ZYUU\UώYY\\XYWZW\YX[Y]Y^^WVZ^UWUYYZώW\\VYZWYYYXWYZYYY[ZWWVYYYU\YV\\WWVZYYUYW\ZXW^ZYXXYYY\WZWYX^^YYVVTWVWU\WWYZZY[\Y\\[[\WX\W[W^^WVVVVW]W\\\WZZZY\[XYYZZWVZ[ZUVZY]WYXUUTTWWV[\[W]WWXWWZUUWYZUZ]Y[[[[VVV[WWX]\T\UZZ]WWWWZXXZX\\\W\YY[VWXVVVTW\ZV[[\ZZWWZUZZZ\[\YY\YW[[W[YYVVT\V[T[\]\UU\ZZ[Y^^WXXXY[[]UV\YWU[Z\[[Y^]VYWZZW[\X\Y\\Z^]Y^XWZTT]]VUT\XTZX]YY[XVY\\XYWZ[[YYXZZ[Y[WUV]YV]\Y\^XZ[\Y\XW[WZ[UY[XZ[[TTXV\[VU][[YYYW]\XVXXV[Z[^\UYX^TTUTTWUXTT[XZYX]Y]\WVXZZW\\W\XXY^VTTT\[]UU]XWZZX]]\WWXZWZZ\W^YXW\\YYXX\]UY\V]\Z\\[ZYWVZ[Y[Y[WYWWYWTTUUW\Y\UU[X[[ZZXVZVX[WZYYYYVWWVTYU[U^Y\\\[V]XV^XY\\WT\[\[\ώUWWTVV\TVVY]\[\\X[XX\[\][[ZZώ[ώWWVZZ[\VYVXW[[WWXY^\\[ZZώ
]^Z\[W\UVVV]YW[]\\]XώVVWWWT[YV[[XZZZZώUW[WWVXYWWXZώWVWTVVVWώVWVVÿώ\UU\ώ[UZYYZZ[ώUXW\WWWW[WZUώUZYWW[XWWWYU[ZY\ώVU\]\X\XWYZX[^[YZZW\ώ
\\YYW\XW\\YY\Y^^W\ZYUU\UώYY\\XYWZW\YX[Y]Y^^WVZ^UWUYYZώW\\VYZWYYYXWYZYYY[ZWWVYYYU\YV\\WWYZYYUYW\ZXW^ZYXXYYY\WZWYX^^YYZ]VXYWU\WWYZZY[\Y\\[[\WX\W[W^^Z]]]ZXW[WY\WZZZY\[XYYZZWVZ[ZUVZ\Z]Y\YUWVXWZY\[W]WWXWWZUUWYZUZ]]]^]^ZZYYWW\XZVYUZZ]WWWWZXXZW^^\^]Y\^ZX[ZZZWW]ZYXZ\ZZWWZUZZ]^]^^Y[YZ]^W\\YZZW]YYVTXY\UU\]Z^^]^^^^YUZ\^YY^\ZYU]ZYWWWYY\\^\^^\^]\]\YZ^_YZUW\YYVZ]YWYWTZ]]]ZYYYXYY^®^]]]\ZYYWXYY]ZWVW[\Y\Y_]_]ZYU\\_^]ZZ^ZWYXWVZZWVVWVVY\ZZ^]\YZ^_®___Y]]]ZZUWY]YWVYVWYY\ZZ]ZYX_®®®^^__[YTZW]YVWVVVVYUY]WY\^Y]®®®[]__^Z\\\Z\\YZVWYYYYXZ][^]YX]^]^^^^__ZZ\Y\ZW][WWVZTWY]Z\Y]^\]]\^]_\]^\ZY\]]WYX\VZWVWVZ]\Z]ZZ\Y^_Z^]]_\Z[YZZVW\YYVWVWV]Y\Y\^ZZ[]^YZYZ_YZ\[]]WVUZVWVWVW[Z\\Y[]\^_]YZZ]®ZZ^ZZVYWVWWZZYUYWZ\^^^Z^_\^YZ]_^YUY\\WVVYVV[]Y]V]Z]]X__[^[YZZ]_^^[Z\ZYWZWWVX[[^YUZW]]Y_[^ZY[]^_Z^ZZ\Z[WWVVW]Z[[YYYZ^]Z]^ZYUZ]^Z^Y^\YZZYZWVY^[W[_UYZY]Z]Z[Z]ZYZ[]\\Y\Z[[YVWUY^^]Z_YYY_^ZZ\Y^]___^\^^ώYWXWYY]W]^[Y^W^]ZZ[\^__®_^]]ώWWY]ZXZ]_ZYW\^W\Y]^_®_Z]ώ
YW]W[\^YYZZ^\\^^^®]ZώYZXWWVYYZ]^\]]]ZώYTZXTZ\YZZ\ZώXYWWYYZZώYWYYÿώ\UU\ώ[UZYYZZ[ώUXW\WWWW[WZUώUZYWW[XWWWYU[ZY\ώVU\]\X\XWYZX[^[YZZW\ώ
\\YYW\XW\\YY\Y^^W\ZYUU\UώYY\\XYWZW\YX[Y]Y^^WVZ^UWUYYZώW\\VYZWYYYXWYZYYY[ZWWVYYYU\YV\\WYVZYYUYW\ZXW^ZYXXYYY\WZWYX^^YYZZZWYZU\WWYZZY[\Y\\[[\WX\W[W^^WZZZZZW[YY\WZZZY\[XYYZZWVZ[ZUVZX]\\XUZTTWZX\\[W]WWXWWZUUWYZUZZZZ[[[VVVZWWXWWTUUZZ]WWWWZXXZY[[\[[]V[VWY\[Z[WZZZWW\ZZWWZUZZZ[W^[Y]VW[[Y[YZ\\Z[VVZWWZ\UU\ZZ[[\[V\]VTZZ\ZZ\YYUUZWVSZWXXY\[\[\VZVYYVTZ[]\XUU\UXWZZVSUWWWYZZWZVZ\[Y\XZZ\\\[VZZUWZYZTRTUYUYZZV\Z\YUVX[[Z\\[WXUUUYZW[VTUTYYYVVZ^\]X[XY^]]\\ZYXZT[ZZZZWVYYUZ[UW][]VZTVZ]]]\XYWXXUXZWVYYYUUYZUVY[]VYTX\ZX\]VXXXWXTXZXYUYZ[ZZUW[[XX\\VW^\XYV[XXYTZTYXZYYX\[UZWXYZYZUYX]\\\[X\XYXST[[T[[ZWVTV[ZXWWWUX]WXWYYVX\ZWXYXYTY[[XW[ZXZ\YYZVY[]\YYVWZX[ZYYYXWSUZYZY[ZYXWXYXUW][[YYWW\ZU[[\ZVVRTVWZ[UYWXXWYXVW[YVUXVZZ[ZUUY\WVTUZY[ZY[VZX[ZXWV]VWVX\^Y[\WW\ZZXXWWZ[XXZU[ZW[ZXW]\WWYXWZZVZ\YXWWTTTVZXXUTYVWY[WW]ZXWY^ZW[Y[YYWWYXTYT\XZXZYUXW[\ZZXVVTXVXZZY\YVWWVTZUZUX[ZYZZWYZVTXY[\^\\[Y[\ώUWWTVYZTXVYX[W[VVT\X\Y^\[[ZZώ[\VZYWZVVVX[[VW[XY[^\\ZZώ
UTZWUWYXVVVWYY[\^\\XώVVYUTTUUV[[[ZZZZώUWWWWVXYWWXZώWVWTVVVWώVWVVÿώ\]X\ώ^][ZYY[\ώ^]Z]XZX[]YYWώ]Y\ZZ^]\[]\]]Y\]ώXWY]YX\Z]YXZ]\]]YY[\ώ
]]Y\[\ZY[[YXY[\\ZYZ[\W\]ώ\]\]^]WYY[^][]\Y[\W\Z\WVZ[\]ώY]\XZYWXY\XWY[Y\ZWZY\]]^\WY]XY[]WYY\\WYY[ZYZ\]]^]YZ]\Y[\]X[]Z[Z]VXYWW\X[Y[Z[]\[\Y\[\YZ\]\YZ[Z]]]ZXW[WY\YZ[[][]Z[\[Z[X]^YWXZ\Z]Y\YUWVXWZY\\Y]ZXZYYZ[]]^YWZ]]Z^]^ZZYYWW\XZVYWYY]XZZ[YZZXW^^\Y_[_^ZX[ZZZWW]ZYXW\[ZYYZWYZ]^]^^Z]^_]^W\\YZZW]YYVTXY\XW\]Z^\]^\^]]^®\^YY^\ZYU]ZYWWWYY\\^\^\[^]\]^ZY\_YZUW\YYVZ]YWYWTZ]]]ZXZXYZ]^ZVX^]\ZYXWXYY]ZWVW[\Y_\_]ZZY\]^\ZW[YZ^ZWYXWVZZWVUWVVY\[\\WYZ]_]Z\Y]^]]][[UWY]YWUTVWYY\Z[YYXYYZ[[^XZ_[YT\W]YXWVUVVYUY]WY\^Y][ZZ[][Z^Z\\\Z\\YZVWYYYYXZ][^]YX]^]^^^^[_ZZ\Y\ZW][XWVZTWY]Z\Y]^\]]\^]_\]^\ZY\]]WYX\VZWVWVZ]\Z]ZZ\Y^_Z^]]_\Z[YZZVW\YYVUSUV]Y\Y\^ZZ[]^YZYZ_YZ\[]]WVUZVWVUVW[Z\\Y[]\^_]WYZ]\ZZ^ZZVYWVWWZZWUYWZ\^^^Z^_\^YZ]_\YWY\\WVVYVV[]Y]V]Z]]X__[^[YZZ]_^\[Z\ZYWZWWVX[[^YUZW]]Y_[^ZY[]^_Z^ZZ\Z[WWVVW]Z[[YYYZ^]Z]^ZYZZ]^Z^Y^\YZZYZWVY^[W[_UYZY]Z]Z[Z]ZYZ[]\\Y\Z[[YVWUY^^]Z_YYY_^ZZ\Y^]___^\^^ώYWXWYY]W]^[Y^W^]ZZ[\^__®_^]]ώWWY]ZXZ]_ZYW\^W\Y]^_®_Z]ώ
YW]W[\^YYZZ^\\^^^®]ZώYZXWWVYYZ]^\]]]ZώYTZXTZ\YZZ\ZώXYWWYYZZώYWYYÿ