þX
 ¢þUWYTVWW	þYD£¡¡	¡A¢£þYV¤VV VVW 
VUVCþVWT¤ U	X]ðW VV	WVVþ
 X¡WU ¡V“¢“	X]ðWY	XX¢V“þ£ UUWU T¢ “X¡WV ¢“ V WU X£Tþ
  X WUUVU	UUWU“X¢VC	 XUUX¢VUZþ
XXUWW WUUW XXXYX		Wþ XU	UVWXYX
 U¢¢WUXU	XWþ
 ZVW 	UXU	X	WòXTYX	þYUD[TXXYX	ôX	]þV
	\W CX
YVXþV£¢	 YVXþXYY¡ÿþ£ WþWUX	UþXTU² UUUUY	þXWT
UVRUVW
ZWU	þZW	[UUU²UTXX	\\BWYþ
WTV ¡X	XSWX²Yû[WTWYW	þVVTV¢A UU[		UX^
WTT[AXABVþWUWS QT¡ WWXVU[\	
R²TS	WYWV 	þUQTRRT²²WUW
UW
T ²UXTUWVY[þURQSSUX	X	SYT¡U
£¢U²VY[þ
TQSX]XVUYVSVUUW\XVYþSVWSWVRU
V TVYþSRTTUWU TXY
þRSRTUVX[þQTXYÿþ¡XVWþV£
V
²Xþ0² TUVU
\Z
þ		U RUVX
ZZ[ú\þX	WV	ZU°T°]]B T¢þ
UY¡¡¡U
UW£ñS[üWTX
X [þZT
ñ¢   V

UX_[XU0[0Y ¢ 
\þUSñUWU¢¡XWY X\ñW
²²TS	WZXV ]Zþ°0U UT²Z¡
UW
0
²U	TUX X£\þU¡T ¢[\XWTZT¡V	W[VUUVT¢þ
SY[\^VXZWSW  ¢  	TWþZXT°XXS
W¡X

Y Xþ°XW°UU¡XZ	
Yþ²VWX¡Y¢VþUW¢Vÿþ	ñþ

óþTþ	Q	ðüþó
	ððR
	
úúT	þ
S


R	öú	
	þSXTð
ö	T	óR
TWåþã		ú	
úQ
ö	ð
üþPSTRR	üä
ã		þ	


ã
å	Rþ
R
	ü	ðö		Qþö	P
þñ

þóR
	þÿþ£ WþV£
V
²Xþ0² TUVU
\Z
þ		\Z\\ZZ
Z\[ú\þX	ZZ¢þ
UZZ[þZZ
þUSñ]ZþZþþ
LNNþZ\N\Xþ\XZ\Z\ZXZ	
Yþ²VWX¡Y¢VþUW¢Vÿþ££¢ZþYZZ¡XVWXþ£YWV£
V
²XYþY^Y0² TUVU
\Z
þ£ZY		U RUVX
ZZ[ú\Xþ
£Z[X	WV	ZU°T°]]B  [Vþ£XXUY¡¡¡U
UW£ñS[üWTX¢ 
\	þVXZT
ñ¢   V

UX_[XU0[0XV ]ZWUSñUWU¢¡XWY X\ñW
²²TS	 X£\	U\VRR°0U UT²Z¡
UW
0
²U	TT¢ZYZY\	ST°SU¡T ¢[\XWTZT¡V	W[VU	¢°V[^\VW°°°²SY[\^VXZWSW  ¢  	²	
\]UBTT°°SXZX°XW°UU¡XZ	
YUX	[
\\W¡ 
TU²VY\U°U²VWX¡Y¢V		\Z]\\\\VVYW V°\\¡US°SUW¢VXWW
_Z_\^\V  W VT[^[UXUU°TU¢Z X\]^W^\]XY UY V[^XBZSV²°	VZI]_	\]\\TWW¡V	U^]]VUV\RV
ZI\\W^\^\SWUXW	V\^\WWUñ]U^I^H^]^X\úZ XVWTXS^^BW
	WVW^^\]I]H	[^[¡VRXVV0YZVXV\\\\W^\]\XRR0TX¡ YWXZ[\] [^[^]]USSRV[\WV W	TT]][^^\^VX ¢XU 	Y\ XWTS]]	
H\]\\U ¡T	¡XW\\\ZY£¡	 []I\VX]\]^_WXW Y¢V
]\U°XB£ B^Z	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡T  ¡]\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿþ[[£ þZYWUYWXVþZXTUS T	SZWþZZXWT
T±TWURSZUþZ£ZW	[TRRST¢WTUWþZWWTU  Z	SR±±[XSWX\þ	TVUZ£XST  
	URWS	[\ZþZ£WXT[	RTWW
Z[	XTWü	VZ¢^YþWUZUU ¡	 U [[_	VZR
^[þS  TR0 W¡	X[ZV
Z	TZ
\þVSUSRS^Z\^\	]
\^
SZW	[\[^þ	 UTWU[ û[Y \[W^\W
WZ\[]þDVTYX

UW [UXZ\\]^¡þ\VUWZ\XSWW_üXZú\]^ZþVZVTWXX]	û
\
^\^]\þ ¢D£X
USY[Vü	YXXXZ]][_þY ZW¡YVRYX[T°UUSW^^^\ZW^þW
WV[X¢V
_VTTVUSTT[\\XZþWYW	U	XX^	°V¢
S[X°S¢V ¤]\þXV YWR]I UU^VB¡	X\¢V[üþVS[	WV[US
S TU¤[_]_Y ZþUSSTXZW	£ °U U[^^[	W[þUU±SUUW
£ US	_^[¡¢XþX ¢VVSTTWX¢\S^_OZ]XXþ ¡T	 ¢XU Y\ZXU]\\
V\]þXW Y¡T	¢X 
WBWUY\X\ü\_ú^ððüþVó¡¢W Y¢\¡
WW\YZ]XX_Hú]^_^VUWVVW	Bó¡¢¢\]Y	VV	X^_^^^^üü[	\Y\XW YW	BBU°X^

	X_H^]^\¢\X\Vó¡¢¢
£B¢ ¡U \[_\\WV^[ZVW	BX±X¡WVV¢UU Y_^_I[ü^^ZUX	W¢ðBYY	¢WW¢	¡SZ_^
[ü^\\ü^W]\Zþ±XYY	
UWX	 T]^
X]]^\UZþ¡	W	XUWX[WW	[U\]I]Oþ	W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿþ¡	¡þV VVW 
þ U	X]ðW VV	þU ¡¢“¢“	X]ðWY	XþWU T¢ “X¡W¢ ¢“ C WUþ
 WUUVU	UUWU“X¢VC	 XUUXþ
XXUWW WUUW XXXYX		Wþ“VVU XU	UVWXYX
 U¢¢WUXU	XW
VY[TTTATW ZVW 	UXU	X	WòXTYX	XVVZ¡“XTTAA YUD[TXXYX	ôX	]WWX
]^^]ZYVV XTTU¤V
	\W CX
YVXU¤
Z]]W	WXFWXVW “XV£¢	 YGXVY¢\\]]ZXU¢W  £WTTTXWXYY¡¢YUZ\]^]]]W	WWU TXVUVTTY¢Y
Z\^_\\]¡XU¢W¢WXXW £ TY\]]]^^]]^^]ZYVWU TTFV£ ££¢X\]\^_\]W	WXF¢WXC VDW“¢^]]^^^\]^¢XU¢W  TFV£WVW£V]]^\]^]]]]FWXWU TXVC VDYVDú]]^^^_\]^]^\[XX¢WXXWWVW£W]]^]]^[]]þ
ZWYTFV£ £YVDú]\\\^\^ûþ
VC VDW“W^]]^^I^^þ
\Z¢WVW£V]]^^\^^þ
\
YVDú\^Oþ
ZW^_þþÿþZ[£ þZYWUY	UþZ^XTUS UUVUZþZZXT
TST¡TWZ
WVþZ£[W	TS°STZWW	[þZWWTWU  X	XS°°	[Z[þ
ZWVVTñXUBWU	WV
	
[^þ££WUUTUXZWYZYXT[	[[]óþXUWS SXZDW\[_	UX°U]
þSVU°X[UV[Z]X\Z^UWT\\\þV	W^Z[Y^\\S	]	_ZSX]_\^þñ	ZUSUZX	XYü[UY\^
^[þ	Wñ XUW^YWTUü[TZ^_þX	WYWW\^XXX[\Zü
W[^\]þXX W\ZWY°	\¤_^	U[H\þVYW ZU\ UUV]_ü	YXXXZ]üþ  W SYWTZ
[][T°UUSW^^^^\þY UYUXWXV^\_VTTVUSTT[\\ZþWW¡VVUXS^^	°V¢
S[X°S¢V ¤]¢þ\[XX¢W []I UU^VB¡	X_\]^]^þ
ZWYTU[US
S TU¤[_^[]]þ
U£ °U U[^^[\^\^ûþ
ü
£ US	_^[^^þ\WX¢\S^_OZ]þ
ZW^_þþÿþX
 ¢þUWYUVWX	þY¢£¡¡	¡ ¢£þY £¢V  VW 
VUCCþWWU¤ U	X]ðW UV	WV þ
 X¡WU ¡¢ ¢ 	X]ðWYYXX¢¢ þ£ UUWUUU¢ UX¡W¢ ¢  CVWUUX£Uþ
 UX WUUVU	UUWU X¢VC	 XUUX¢	UZUVVU XU	UVWXYX	UU¢¢WUXU	XW
VY[UUUUUW ZVWV	UXU	X	W	XUYX	XVVZ¡ XUUU  YðCZUYXYX		XW
]WWX
]^^]ZZWV XUUU¤V
	\W CX
YVXU¤
Z]]W\ZX¤WXVW  XV£¢
 Y[XVY¢\\J^£\Y¢WU ¤WUUUXWXYY¡¢¤UZ]]^:J7JJWU UXVUVUUY¢Y
Z\]^\^^:678IYX¢WXXW £ UU^]]]^[^^ü:667I6KJWYUF¢6:[£¢ ]\]]\^þû6þ6EFJ8þüJF[::IX  ^]]^^\­KHþDE75?J76997:\XV]^^\]JKJKþ667©I9777:9V£\^K­JMLNOKþIII7:þMFDJ­ZW^_OþKMKK7JJJ^þH^IJIM_J67©­þ:þ:J;MMGE7JK_þIJHH5HJHþ9þ®GG:þ:JK_MEE7K­þKJED5H^HþIF79:9JJIJ7JLLLþ^JDD5I^^þOJIHJJKJKNNMLJþ6I67IJJ^þ	I:JJLLNKLKþ7:MKJJJLþ[\\]L^ªJI7IKJ6þJLIJ7þ67JLKNI7IJG:þIH56þ666=99J?ü?:::=;Jþ	67þ6666;G9;J>>::?þ	IHH66þ667:þJ:?K;E:þ;=þ	KEE6H©þIJþJKMLJJ:þJJJþ
EE6I©©­üþL­ª;:þ;G9:þ	677IMþ©^^^:;þ:I::þ^^þ7767JJJ::=þ:þ7FD7JJJJJ:Jþ767:J:þJ97þ9:;Oþ;þªIÿþWW TþUWVVTXUUþ£UTðUUVVWðUYþVðT
UTWUTVV T U
Tþ
UUW YUT  TWT£VVUUTðTþUVW XVVUTTUUTU UUWVU	UUTUWþTT	VUWVUTVUUUTU£ T£ Vð£XUVðU
þTTTTVWUUUZUUXUUVðVTXTWUWUUZI7TTTTUVU55W UUVWUUTVðWT	EFJþZðW  55\VWWVUWV	 UY
JFþ55T56H[	V UU W WW£[[þ
]YHI\W U VU 	TðZ[Zþ^	TTU£Eð£[[ùþWWTTTWWX
Z]þ£WUU
Z]þ£W]ÿþX
 ¢þUWYUVV	þY¢¢  	WU¢Xþ
U¤¢V  VV 
VUWWþVWU¤ U	X]UW UV	VUþ
U¢¢WU  ¢ ¢U	X]UWYYXX¢¢UþX UUWUUU¢ UX¢W¢ ¢U   WUUX¤Uþ
 UX WUUVU	UUWUUX¢V 	 XUU¢¢	UZUVVU XU	U WXX3X	UU¢¢U¢3H]

VYUUU5UW ZW\ZY365		W	XU¤5H]\^V^  576  Yªªª_5IIH			X
]
\\©^^]Z
IJ©I7\	©I77X
XV¢UZ
ZH77H]W
\YGZ^55¢XZ_]H79
G¢VY¢\J96FI^F
V¢WU F5
^UZJI¢¢
UZ\]::I]]FFHXU U35^¢YZ
ZIJ_<7:J^:JKFH¢W3^_¤HXUU^]::GK_JJI:;;J;OIG\¢Z¤]IJJH¤¢U]II7KM^^<<76^IIFI7667GF:_
 U^]]I76JM^þK77JHI_þ7FF7FFJI6¤U]I:97Jþ>JIþI^^]75F::JKFI7\JIH_:99Mþ>?Fþ_I76F:;OIG9I^^^7KIþIJ>þK<GþIII7_I:FGM©©K^þKLMLJIþI77GIJH7FF­HIHIIþI:<JþK78:JþIJ©KHIH7I^LIþGI<K®þJ779:þJL^H_I67H^^Kþ<::N:K¯þ7MLKLJ^©J77656JM_^^þLO¯_þ­O^©KþLLI67F79N7679<<LILJþª©©þK7JJI7F¢FJKJH7þF5©þ©¬<J_LL876<IKNLJþ44_Lþ©^__^^6F79I7<O?¬þ55J7þ©JKOMK76IFF6J>M_þ6G765þG^65HHHJIFI]F:NL77þ©F 4þ^J5FFFF;JIKþKOMF6H]þFþI97:þ::MKþNF6þH©IKIMNIJLIþIþIþHH5ILI5FþFHNOJGFFþNO__þHOþK^ÿþ:X
þGI:J>	Z\þ79:9?L:?GZ[þ6JGC6JHKGJ]]¡TþJIIEJ¦D6HI_L6<YTX
Xþ
K
JDC5KL:JH_üü[YX	]TYTD¡þWV	Z9CD5I^^__KJ566L[[	ZXV¡]þTTT	:EH57H¢H]L>K:DD7KHTVXVX£\XVT	4G\E95[[\F<WI8	5I:I7VVVT¢ZYZYWY64¨VGJ[\^WV
[WWTYEDJ
TWJFT
[C£
V§[§©^YTTXXW
¢X

ZVXTVJV:;HH\\TVV§J]§TXWT6F[[	
YVZVVJ\
:7GIIZXYWHVTVT	99XYXVX	\ZVZ]I6G7I6KHI]^	VY^;:9VXWW
_W	Wü_\ü7H6CDJ76];[Z§\H98[VX\]^	TX^ü__	CDH;^K:LX£]]W;:VZI]_WX¢\]^]WEGHJHK_LH^H]TIHFI\\XVX^]©\	JJ[76J®J	F57	]E7J_H^]^	V[©©©©ü
KJWKI:KKCWGH]	HJK;I]H£©]^­®­__VXXV]©;;JDE5I©]LJ;K\][
W^\^^^\	X>K\?<I5HJLL]]J]JJ]]X	Y^©\]4I9J¡[\X¡V	[H57H;J[T
]¦^[^
£Z
T^\WVVXZ[ZüIJ;IXVX_]^]üõTXXF^]VXXW[§]];J
I
ù^ZV¡VTF7^]T
F7H_üLK_?JIGJJZ[[[[TT66üVT767JI:;LKJJ9JJ;[Z^]G¡XX77[FW4666IEIJJLKJIZüLX^^\¢¢T	GHH67ZE77:;JLKKCJZIJ\ü\\]\\	X¡Y[CC6H]]HH;JLKJIIZJ;;J\]^V	¢¢ZCC6H§[\^üJ_©\JJ]IGIJ^^[\]VW	CE7IH^[[¦\[9J]^_IIJJJ©¨¨kX¢VCE7©^ü[G77H;;;JJJ]]Z\I:\^©_\XTYZ\]__X7EC7;;IJ;:J]]ZZ\Zù\þZY[\]]^
768:;J\J98]\¢¡\\]þ\X_^\V77::J\^_JJ][TZ^Hþ
^^\V	HHJ[F^^^_ü^XZ\þZ]¨HF7^_\þ\YYW66^\þ\Z77\ÿþUVWVþWXY
VUX6þUXV	G66WE778þVXUXVXE6H\XHJ
UVþGWVUXUUVE6H[[^	X[þ
JIJ5U
UU68GXX
Y[8[YXþX]I978VUVX7]UXVVVVVWG[XþG6GXXXG::G
X]ZVUUVUUWVUGWVUVWUþX	VVW
III7H
	[UU	VUXUX	VXWþUVWWJED6I

UUVVV:[ZWG:þ
VVIGE7K\\	VW8[G\[þHIKMOM_
[Z]:H7þ¯_MI\\[Z	M:þ8[]^]IþH557ÿþ¦XYVþLI9:X
Tþ669GI:J>	Z\ZþHID79:9?L:?GZ[þI¨H6JGC6JHKGJ]]¡TTþ
76IJIIEJ¦D6HI_L6<YTX
XVþVZHK
JDC5KL:JH_üü[YX	]TYTD¡
þWTTWV	Z9CD5I^^__KJ566L[[	ZXV¡]ZþTT	:EH57H¢H]L>K:DD7KHTVXVX£þG\E95[[\F<WI8	5I:I7VVVTþ
VGJ[\^WV
[WWTYEDJ
Tþ©^YTTXXW
¢X

ZVþ§TXWT6F[[	
þVT	99XYXþ;:9ÿþE6H\þZEE6H]©^þ		677HZ	]]^]þ8Z£	67^][[7767JJþ7::H[6^]6775D6JJ:\þ
46HHIII77\^]56667:J:úZZ	þD44DZ
KED5IH657799:^£	6:	£þ56D47HZ6IHE7K\^68JIKJ]H
:8:H£ZþD7:6£K7IKMOM_^HJ©^IH6<<9J;Jþ:6ZHK®_MI]\^ZZ:;::6þ
5IJ­[H
H\J]9:::D:ZþJ_HGG4567J:JIþZZIDD4EH::JþHDD4G997þ6ED9ÿþ\£VYþEON^¨§^þUU]^Hª]Y¨§\UþUVU¥ªY2XXUU_§£Y
þ¢UUXX]ZVUUUWWUWW¦¦FGþ
ª§[[XW¥WUVUZUUWVWUYHFF¦WþUVZY[GF¤E§WWWVUVUUUUH©ª]X©¤YþUVUUUUUHH¨§£UWWUUUWWZHHXEH		[¥\
þUW¥UU
2Yª§WUUUWW[Z\
[XUXW¨þWUUUEHUEJ^UU\£MMZMVUþ
UU	V¤£F_H©^J_WWZZJMþü§¦H[¨^ZXXU[[^©þ¤UUEG¨§§J\N2þVUWVW]KMþWZLGÿþLþJJþMMLHþFGKþDFþGJHJþKþ1JþKIJFKþHþHHþEIMKþFGNJþKGCKKINþKGþIJHþGIþ	GJþKGþMþHIþLþDFGCDFJCþIHIþJHKKþHþHþGþKJGþHþIKþKþJLHþJþJþDHþJIþFþJþKFJÿþJYþJõJþøøö
øYþWVW

õK
öþCZXWYTTXLKõöJYþKY£¡ W CU

JIþø[öJVWX 	UUöøöYþ÷

YW¡ V
XTWø
øL	Yþ
£¡ 
YK[\ñYWXU£øKL[þ¢¡WUVWXøõ÷öY¡¡WSU W\Lþ	UWUW¡ V
ö
[	 YUTUT[þLK
YVSU\ñYL÷JYñTþLLKK£¢¢ ¡¡WøK

Y[\þ¤£B¢øöôY¡W¡	 YUL

ö\þTWWV£TV÷L÷
öZWSUSYñT\[^[þ[Y¡ VXT¡ VKM
ZSVTñ	WZù[^þöööYW 0V£¢£øMJLYUUXV]]]]^þ
÷ööYUUVVT¢£¡


[^^[\[þ ¢TWL÷÷[YUTWVTUWøY
^\[]^ W¤RU0UWøø÷÷[YVRS ¡	S\[]][þ U¢ UUS0ö	YUXTVû^I]þSRUW¡SUWø
õôYWU\þ
0A¡VWWVUøö

[ü\_þUWTVSWVñøù^_þ SSYTZSU[\þUTU ¡WU\þ¢	RWÿþJYþJõJþøøö
øYþWVW

õK
öþCZXWYTTXLKõöJYþKY£¡ W CU

JIþø[öJVWX 	UUöøöYþ÷

YW¡ V
XTWø
øL	Yþ
£¡ 
YK[\ñYWXU£øKL[þ¢¡WUVWXøõ÷öY¡¡WSU W\Lþ	UWUW¡ V
ö
[	 YUTUT[þLK
YVSU\ñYL÷JYñTþLLKK£¢¢ ¡¡WøK

Y[\þ¤£B¢øöôY¡W¡	 YUL

ö\þTWWV£TV÷L÷
öZWSUSYñT\[^[þ[Y¡ VXT¡ VKM
ZSVTñ	WZù[^þöööYW 0V£¢£øMJLYUUXV]]]]^þ
÷ööYUUVVT¢£¡


[^^[\[þ ¢TWL÷÷[YUTWVTUWøY
^\[]^ W¤RU0UWøø÷÷[YVRS ¡	S\[]][¡V U¢ UUS0ö	YUXTVû^I]]\XRRSRUW¡SUWø
õôYWU\[^]]USSR0A¡VWWVUøö

[ü\_^^\^VX ¢XU 	UWTVSWVñøù^_	
H\]\\U ¡T	¡XW\\ SSYTZSU[\VX]\]^_WXW Y¢V
]\U°UTU ¡WU\	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡T¢	RW]\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿþV þWW	Yþ
WB	WXUYþVH£XTV¡WþZ	VV£UVXXWXU¡ þZV££VVXTVVWUVþXVW¡VVXVXXV	¢	¢þY	W VWWVXU	XSX	¢	XWUþ	T	WTWZX 	U	XVWVU[XZXWYþSWWW£YZTYVW
V¢ VU[XVUY]þ 	W£¢WWTVXW¢ 	T¡VWVVY[þWBWWBWZ UW¡	WWW WUYð	W]]þXUW VZVW
 ¢WY W¢WóWVWV[]IþTVVWUV	¢ VWW¢YóB	WV	Y]\þVXXV	¢	¢W¢WW	WY WVVY\\þXU	XSX	¢	XWU
WW
¢WWóXX[]^þ	XVWVU[XZXWUX¡XVXW	WV^]Zù[þVW
V¢ VU[XVUUVV	YYB¢[^]]]]þXW¢ 	T¡VWVVU
UU	YYXVY]^[\W¡	T¡Y WUYð	WUYXV	W	¡Y][^\[]þY W¢¡óWVWVYYVUXW¢ Y[\[]þóB	WV	YUWWVWUWV¢[\]^Iþ
 WVVUWY¢VX XXVZ\\þXXY¢£ UU£
X[ü\þ£ X VWVZX]ùþ	VñX ^þXY]ÿþV þWW	Yþ
WB	WXUYþVH£XTV¡WþZ	VV£UVXXWXU¡ þZV££VVXTVVWUVþXVW¡VVXVXXV	¢	¢þY	W VWWVXU	XSX	¢	XWUþ	T	WTWZX 	U	XVWVU[XZXWYþSWWW£YZTYVW
V¢ VU[XVUY]þ 	W£¢WWTVXW¢ 	T¡VWVVY[þWBWWBWZ UW¡	WWW WUYð	W]]þXUW VZVW
 ¢WY W¢WóWVWV[]IþTVVWUV	¢ VWW¢YóB	WV	Y]\þVXXV	¢	¢W¢WW	WY WVVY\\þXU	XSX	¢	XWU
WW
¢WWóXX[]^þ	XVWVU[XZXWUX¡XVXW	WV^]Zù[þVW
V¢ VU[XVUUVS	YYW¢[^]]]]þXW¢ 	T¡VWVVU
UU	YYXRY]^[\W¡	T¡Y WUYð	WUYXV	W	¡Y][^\[]¡VY W¢¡óWVWVYYVUXW¢ Y[\[]]\XRRóB	WV	YUWWVWUWV¢[\]^I[^]]USSR WVVUWY¢VX XXVZ\\^^\^VX ¢XU 	XXY¢£ UU£
X[ü\	
H\]\\U ¡T	¡XW\\£ X VWVZX]ùVX]\]^_WXW Y¢V
]\U°	VñX ^	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡TXW]]\Y[X]\\]VVW	BBW\WV ¢U0¡¢¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿ þFHH6þ]JþJõJþ]ø
öøøþö
Kõ

[Z[þ]JöõKL\XX][\^CþIJ

YC [ ¡£]Kþ]öøöYY	 \[ZJö_øþ]	Lø
ø[X\
Z ¡[]

÷þ_LKø£Y\[]ñ\_K]
 ¡£þ
Y\[ YW[¡¡]ö÷õø\[ZY[¡¢þ
ZYXY] 	_
ö
Z ¡[Y[Y	þ¢¢Yñ]J÷L]ñ\YWZ]
KLþBXRY]

Kø[¡¡ ¢¢£KKLLþBYYö

LY] 	¡[¡]ôöø¢B£¤þXYYZ\Xñ]WYW[^ö
÷L÷ZX£Z[[XþY¡	W	Y[	ñXZW^
MKZ ¡X\Z ¡]_þY ¢WXS\\YY]LJMø£¢£Z0 []öööþ¢¢VWU ¢\_


¡£¢XZZYY]öö÷
þ DVXXBVW]ø[YXZ[XY]_÷÷L[X¢ þ ZWX
¡V Y\W	¡ WVZ]_÷÷øø[Y0YV¤[ ¡VVXZVW£UYX\Y]	ö0WYY ¢Y ]\XRR V
VWV Y[]ôõ
ø[YW¡[YVW_^]]USSR[XñVY_

öøYZ[[Z¡A0^^\^VX ¢XU 	XYUZøñZ[WZX[Y	
H\]\\U ¡T	¡XW\\	TYYYW^X]WW Z\]\]^_WXW Y¢V
]\U°	V
¡ YXY	_]^^]^_\]VV	¡¢¢U^^]¢ ¡TV	¢]\]_\]\\]VVW	BBW\WV ¢U0¡¢^¢]][\
^\XW¢VBBV^XWW¢	X°]^_\]]¡^\^ù_üT	X°X¡VZ^_
UWX[UZú\^]]\ ^\]]]\V ZWX
¡ XVWYX\_\\]_^^WVY XZV^_£UU £UXù\^Z]üþYZW V
^\VWV X	W^^_	]_^þ[XU[^^XñV	V \\_\]][þ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°Z^^þ_Zû]þZ	ÿþ]JþJõJþ]ø
öøøþö
Kõ

[Z[þ]JöõKL\XX][\^CþIJ

YC [ ¡£]Kþ]öøöYY	 \[ZJö_øþ]	Lø
ø[X\
Z ¡[]

÷þ_LKø£Y\[]ñ\_K]
 ¡£þ
Y\[ YW[¡¡]ö÷õø\[ZY[¡¢þ
ZYXY] 	_
ö
Z ¡[Y[Y	þ¢¢Yñ]J÷L]ñ\YWZ]
KLþBXRY]

Kø[¡¡ ¢¢£KKLLþBYYö

LY] 	¡[¡]ôöø¢B£¤þXYYZ\Xñ]WYW[^ö
÷L÷ZX£Z[[XþY¡	W	Y[	ñXZW^
MKZ ¡X\Z ¡]_þY ¢WXS\\YY]LJMø£¢£Z0 []öööþ¢¢VWU ¢\_


¡£¢XZZYY]öö÷
þ DVXXBVW]ø[YXZ[XY]_÷÷L[X¢ þ ZWX
¡V Y\W	¡ WVZ]_÷÷øø[Y0YV¤[ þVXZVW£UYX\Y]	ö0WYY ¢Y þ V
VWV Y[]ôõ
ø[YW¡[YVWþ
[XñVY_

öøYZ[[Z¡A0þXYUZøñZ[WZX[Yþ	TYYYW^X]WW þ	V
¡ YXYþV	¢ÿþ\þ\^\_þ]Z][[^þ[][\\^þ\I][^]\^\\^\HþH\¤^]\\\]þ^]H^]
Y^[_H]þ]\^]^][\]ù^\\þ
]]\]H]\
^[]^]\Y\þ	Y\I]^\H\¤^ù^_]\]þ
ZI]^\úH^^\^^]\]]þ¢¢Y]\_]]]^\]\]]þBXRY]^]H\\\\]H]\\I][þBYY\_]^\]]]]HH\¤^]þXYYZ_][[I]]\^]H^]
]þY¡	W	Yù]^]\]]\^]^][þY ¢WXS\\[\\]]\]H]\
^þ¢¢VWU ¢\^[^]I]^\H\¤þ DVXXBVW\]^[ùZ]^I]^\úH^^þ ZWX
¡V YZ
^]]]]^^]\_]]]^¡VVXZVW£UY[[\[^^]^]H\\\\ZYXRR V
VWV ^][\^^\_]^\]]YZ]]USSR[XñVY\]^\_][Y^\^VX ¢XU 	XYUZ]I^Zù	
H\]\\U ¡T	¡XW\\	TYY^üVX]\]^_WXW Y¢V
]\U°	VY^[	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡TZ]]\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿþ\þ\^\_þ]Z][[^þ[][\\^þ\I][^]\^\\^\HþH\¤^]\\\]þ^]H^]
Y^[_H]þ]\^]^][\]ù^\\þ
]]\]H]\
^[]^]\]\þ	Y\I]^\H\¤^ù^_]\[þ
ZI]^\úH^^\^^]\]]þ¢¢Y]\_]]]^\]\]]þBXRY]^]H\\\\]H]\\I][þBYY\_]^\]]]]HH\¤^]þXYYZ_][[I]]\^]H^]
]þY¡	W	Yù]^]\]]\^]^][þY ¢WXS\\[\\]]\]H]\
^þ¢¢VWU ¢\^[^]I]^\H\¤þ DVXXBVW\]^[ùZ]^I]^\úH^^þ ZWX
¡V YZ
^]]]]^^]\_]]]^þVXZVW£UY[[\[^^]^]H\\\\þ V
VWV ^][\^^\_]^\]]þ
[XñVY\]^\_][þXYUZ]I^Zùþ	TY]^üþ	V]^[þ]]ÿ21þVR	þ	ST°SþVW°°°òþUBTT°°SñðþW¡ 
TU²VY\ððð2þVVYW V°\\¡U
ñ32þV  W VT[^[UXUUñðþ	XY UY V[^XBZSV²°ðððþTWW¡V	U^]]VUV\RV^ò23þSWUXW	V\^\WWUñ]U^]Iòþ XVWTXS^^BW
	WVW]_\]^W^[3þB
XXVU ZüYZVXVH]^]
^\[]^¡VRXVV0YZVXV^]_\X]\XRR0TX¡ YWX_\û	^I^]]USSRV[\WV W	TTùZ\	^^\^VX ¢XU 	Y\ XWTSü\_X
H\]\\U ¡T	¡XW\\\ZY£¡	 ù^VX]\]^_WXW Y¢V
]\U°XB£ B^[	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡T  ¡\[\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿ[þ¡VðþXRR
2þUSSRöñòþVX ¢XU 	ò1þU ¡T	¡XW\\ôS	42þWXW Y¢V
]\U°öñþVV	¡¢¢U^^]¢ ¡Tþ	VVW	BBW\WV ¢U0ð2I632þXW¢VBBV^XWW¢	X]^öý	21þT	X°X¡VZ^_
UWX[U]_\	54þV ZWX
¡ XVWYX_\û	^IKNSþWVY XZV^_£UU £UùZ\	]þYZW V
^\VWV X	ü\_X[^IIþ[XU[^^XñV	Vù^_	]þ
W^V
XYU	[\]][]þüYX	V
[\]^	þ\\X
°]\]þ_\]^þZ^ÿ	õ	÷þVR	õ÷L
Kþ	ST°	IõKG
þVW°°°I	
øõ	HþUBTT°°S	óKKGJL÷þW¡ 
TU²VY\		ôø
þVVYW V°\\¡U	øøJö
þV  W VT[^[UXUUôJKöñ	
þ	XY UY V[^XBZSV²°^õ
LJþTWW¡V	U^]]VUV\RV^]IòIþSWUXW	V\^\WWUñ]U]_\]^W^[MKþ XVWTXS^^BW
	WVWH]^]
^\[]^B
XXVU ZüYZVXV^]_\X]¡VRXVV0YZVXV_\û	^IN]\XRR0TX¡ YWXùZ\	[^]]USSRV[\WV W	TTü\_X^^\^VX ¢XU 	Y\ XWTSù^	
H\]\\U ¡T	¡XW\\\ZY£¡	 ^[¯VX]\]^_WXW Y¢V
]\U°XB£ B\[û	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡T  ¡]\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿ[þñôþ¡VøòóøþXRRóõ
÷þUSSRòó
ö	þVX ¢XU 	
õö
÷H	þU ¡T	¡XW\\ôõ÷LIIþWXW Y¢V
]\U°		
L	þVV	¡¢¢U^^]¢ ¡TKô
L	Kþ
VVW	BBW\WV ¢U0öõô	òKþXW¢VBBV^XWW¢	X]^õ	õøøKI
þT	X°X¡VZ^_
UWX[U]_\	
þV ZWX
¡ XVWYX_\û	^IJIHIþWVY XZV^_£UU £UùZ\	]þYZW V
^\VWV X	ü\_X[^IIþ[XU[^^XñV	Vù^_	]þ
W^V
XYU	[\]][]þüYX	V
[\]^	þ\\X
°]\]þ_\]^þZ^ÿþþ4ò]\þS
M[^]]þ4ô3ñ^^\^þñ	
H\]\\þ1ðõðVX]\]^_þ3ðóSò	[]Z^]^[\]þ	13ñô]\Y[X]\\]þðGó3¡¢Z¢]]W\
^\þðK	¢°Y^[\]]¡^\Zù[üþGJNKXUWXZXVú\^]]\ ^\]]]\þJY	XSVUUVXX[\\Y[^^¢VY¡	W	TUU
UVTù\^V]üþBY ¢WXS[VXYUW	S^^_	]_^þ¢VWU UVYYV \\[\]]Wþ
XXBWVWWUYB\]^^
^þ¡ XV¢YW¡\\]]^þ£UU £¢V^^þV X Vû]þ	 	ÿþþY\þôV[^\þó²	
\]þG	SñX	[
\\þH		\Z]\\\\þ31òWW
_Z_\^\þ	25óZ X\]^W^\]þ1óò°	VZI]_	\]\\þS4òS
	¢V
ZI\\W^\^\þXUWXZXU^I^H^]^X\úZþû	Y	XSVUUVXW^^\]I]H	[^[¢VY¡	W	TUU
UVV\\\]]]V^ù]\K¡VBY ¢WXS[VXYUW	V\\\\W^\]\XRR¢VWU UVYYVXZ[\] [^[^]]USSRXXBWVWWUYT]][^^\^VX ¢XU 	¡ XV¢YWS]]	
H\]\\U ¡T	¡XW\\£UU £¢ []I\VX]\]^_WXW Y¢V
]\U°V X B^Z	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡T	 ¡]\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿþôòþ
		]\þ
õô[^]]þõKJIL^^\^þôñ÷
õHL	
H\]\\þ	óöø
öVX]\]^_þõø
Jôø	[]Z^]^[\]þ
õô÷ööñ]\Y[X]\\]þ	ðõ

óõ¡¢Z¢]]W\
^\þõõõõó		¢°Y^[\]]¡^\Zù[üþõð

ôXUWXZXVú\^]]\ ^\]]]\þóñõ	Y	XSVUUVXX[\\Y[^^¢VY¡	W	TUU
UVTù\^V]üþBY ¢WXS[VXYUW	S^^_	]_^þ¢VWU UVYYV \\[\]]Wþ
XXBWVWWUYB\]^^
^þ¡ XV¢YW¡\\]]^þ£UU £¢V^^þV X Vû]þ	 	ÿþ÷õ	þJð
øôôY\þ
	øø
ôõV[^\þñLJöøö	
²	
\]þ÷
	
õ÷õX	[
\\þö

õK	\Z]\\\\þ
ôõ
øö
	WW
_Z_\^\þ		
õøööóZ X\]^W^\]þóñõ
ö
°	VZI]_	\]\\þKôHK÷ôK	¢V
ZI\\W^\^\þ
öõ	XUWXZXU^I^H^]^X\úZþöõøJY	XSVUUVXW^^\]I]H	[^[¢VY¡	W	TUU
UVV\\\]]]V^ù]\K¡VBY ¢WXS[VXYUW	V\\\\W^\]\XRR¢VWU UVYYVXZ[\] [^[^]]USSRXXBWVWWUYT]][^^\^VX ¢XU 	¡ XV¢YWS]]	
H\]\\U ¡T	¡XW\\£UU £¢ []I\VX]\]^_WXW Y¢V
]\U°V X B^Z	[]Z^]^[\]VV	¡¢¢U^^]¢ ¡T	 ¡]\Y[X]\\]VVW	BBW\WV ¢U0¡¢Z¢]]W\
^\XW¢VBBV^XWW¢	X°Y^[\]]¡^\Zù[üT	X°X¡VZ^_
UWX[UVú\^]]\ ^\]]]\V ZWX
¡ XVWYXX[\\Y[^^WVY XZV^_£UU £UTù\^V]üþYZW V
^\VWV X	S^^_	]_^þ[XU[^^XñV	V \\[\]]Wþ
W^V
XYU	B\]^^
^þüYX	V
¡\\]]^þ\\X
°V^^þ_Vû]þZ	ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYZþYW0² TUVUZYVX	]þ[XUUXU RUVXZXUUWVY\£þ
XXVT±UZV 0SWUVVY ’’¢U
þV± U±SVSUWTUSW“ W0V V¡WUWþ	UV±±U T±UU±WW¡XWVUT¢XUXY\þVWUSRS±WV±TS¡¢VTVWU SX[^]þUBUXV±°USVWW± ¢0SVX[[\]þW¡_[VUUS°±UW UXVVW\þVV_’’	XUURT0¢[ X\]^¦\ü\þV _RR°“][SV²°	V[I_\WYX\þXY_UYW°’\V
Z^\WZ_]þTW_W__WWTU¤YU^H^Z[]]üü]_\ùþSW_X_°°¤

¦VWZ^]HWWü\\_þ X^W_	TYW\VWY[^	^[Z]]þB
^U¦¡SU¥ZWV	]ü^¥^[_ù\þ¡Y_T£R¤W¦	\UVZ]ûù_]\ ¦
_ùþVB¥’[WR ^X^WXF\ûü\WF¢¦^þV ¢ YU¢^ \û\¥ü£¥^þVYUS X£^ 
\\^£V
^þ
ZVUSU[\U \[]\¢W	
\þ¢U	USRBXXY\\]þYXX
¡X\[\]þX
±V^^þXV[ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYZþYW0² TUVUZYVX	]þ[XUUXU RUVXZXUUWVY\£þ
XXVT±UZV 0SWUVVY ’’¢U
þV± U±SVSUWTUSW“ W0V V¡WUWþ	UV±±U T±UU±WW¡XWVUT¢XUXY\þVWUSRS±WV±TS¡¢VTVWU SX[^]þUBUXV±°USVWW± ¢0SVX[[\]þW¡_[VUUS°±UW UXVVW\þVV_’’	XUURT0¢[ X\]^¦\ü\þV _RR°“][SV²°	V[I_\WYX\þXY_UYW°’\V
Z^\WZ_]þTW_W__WWTU¤YU^H^Z[]]üü]_\ùþSW_X_°°¤

¦VWZ^]HWWü\\_þ X^W_	TYW\VWY[^	^[Z]]þB
^U¦¡SU¥ZWV	]ü^¥^[_ù\þ¡Y_T£R¤W¦	\UVZ]ûù_]\ ¦
_ùþVB¥’[WR ^X^WXF\ûü\WF¢¦^þV ¢ YU¢^ \û\¥ü£¥^þVYUS X£^ 
\\^£V
^þ
ZVUSU[\U \[]\¢W	
\þ¢U	USRBXXY\\]þYXX
¡X\[\]þX
±V^^þXV[ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYþYW0² TUVUZYVXþ[XUUXU RU
WTXSRXþXXVT±UZVRRR TV\^þV± U±SVSU_XTT±TRX]üþ
	UV±±U T±U[  \[±W[_üOþ	VWUSRS±WVV± ¡VY\£Z]^þUBUXV±°U[S£££¢YR[	R^¢þW¡_[VUUSVSRX [UVB¡		_^Y]þVV_’’	XUUR±WW SS W\^^^[¢^þV _RR°“][SV±WR0 RS^^]^^
TþXY_UYW°’\VYSZ¢^_^^^Z
þTW_W__WWTU¤YU^UY±Z__^^VZ^¯þSW_X_°°¤

¦VWZ^YWZ__^\	Z]¯þ X^W_	TYW\VWY[WT^^[Z\¯þB
^U¦¡SU¥ZWV	]üW_]	]^\\¯þ¡Y_T£R¤W¦	\UVZ]ûù__]Y^^\¯þVB¥’[WR ^X^WXF\û]^\_ü^_]¯þV ¢ YU¢^ \û\[Y]ü¯þVYUS X£^ 
\\^£V
^¯¯þ¯ZVUSU[\U \[]\¢W	
\¯¯¯þ
¯¢U	USRBXXY\\]¯¯¯þ¯YXX
¡X\[\]¯¯¯þJX
±V^^¯þXV[ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYþYW0² TUVUZYVXþ[XUUXU RU
WTXSRXþXXVT±UZVRRR TV\^þV± U±SVSU_XTT±TRX]üþ
	UV±±U T±U[  \[±W[_üOþ	VWUSRS±WVV± ¡VY\£Z]^þUBUXV±°U[S£££¢YR[	R^¢þW¡_[VUUSVSRX [UVB¡		_^Y]þVV_’’	XUUR±WW SS W\^^^[¢^þV _RR°“][SV±WR0 RS^^]^^
TþXY_UYW°’\VYSZ¢^_^^^Z
þTW_W__WWTU¤YU^UY±Z__^^VZ^¯þSW_X_°°¤

¦VWZ^YWZ__^\	Z]¯þ X^W_	TYW\VWY[WT^^[Z\¯þB
^U¦¡SU¥ZWV	]üW_]	]^\\¯þ¡Y_T£R¤W¦	\UVZ]ûù__]Y^^\¯þVB¥’[WR ^X^WXF\û]^\_ü^_]¯þV ¢ YU¢^ \û\[Y]ü¯þVYUS X£^ 
\\^£V
^¯¯þ¯ZVUSU[\U \[]\¢W	
\¯¯¯þ
¯¢U	USRBXXY\\]¯¯¯þ¯YXX
¡X\[\]¯¯¯þJX
±V^^¯þXV[ÿþU	B“ þ	V
¡VC	¢þX
°¢XXX^þVû]^þZ	]^þXX[Wþ			\¤þ		 []Xþ	BB
^YþT ¡[]	þUWV]Zþ	V[¥¥þ\ZY]_\þ Xü_[
þUT¢¢Z\þ[	XSS^Wþ	VUVW\¤þ	V
¡VC	¢þX
°¢XXX^þVû]^þZ	]^þWUVZ]¥þUWX¥\\þWU \
þUX 
\\þ[	U \[][þ[BX^ÿþTX
 þ£UWYTVWWþAYD£¡¡	¡A¢þ£YA¤DV VVW 
VUCþTVWT¤ U	X]ðW VV	WVþ
¢ X¡WU ¡¢“¢“	X]ðWY	XX¢¢þ£ UUWU T¢ “X¡W¢ ¢“ C WU X£þ 
  X WUUVU	UUWU“X¢VC	 XUUX¢	Uþ
XXUWW WUUW XXXYX		þU XU	UVWXYX
 U¢¢WUXU	Xþ
W ZVW 	UXU	X	WòXTYXþ YUD[TXXYX	ôX	þ¤V
	\W CX
YVþXV£¢	 YGþWXYYÿþ RT0þURTRRT TþXVUQRRSS£TþWZVWTQRSWYXVþ	UYUVTVX[WTWVþ[X	VWY¡UTRTTUWþQ[XWYVUUUSSSTUUþUVZZ_WYYWVUSURT0¡ZUþVSQ¤WX
U	\VVSQUZþWWUZ_VZX^WSXXUV
ZþWVW¤\W[¢]VTXYYV^I^þ	XSRQ¢WV£TXU^ W^]\þVWSUX[¢VYXWW\WW\\_þ¢[XYXUWWRYXZZV\\\þRüXYZ^YUQ]UVV\\þVS£X	R]WVURRQSVVZ[þXVRT^YWZYVX
VV]þVUXZVVV\YY__YWWV]þXUURUYXSZûQT]¢XV[]IþZ WSWWWXZZRU^Y¢¢^¤þ
XXYVWWRUVXWXWX¢]^þü^VYZXYWZWUXRüX£]^þRüVYZU[WWVXZU¢ZZ]H]þ££YUZU\[XUVVYRSX]ZþX£
 WVüYUV0UWW^[\þVWU^ £W\WWXXXW£¢Z¢þ^Y¡\XSZ^^WUW0Y^[þü]UVU£UU_\W ú\^þXUZUXTYVXú\^þ	USZY	VVXX]]þU\	ZUVW\]HþVVVXV\^þW	W[ÿþTRRTþRVURQRRþV
TRTPQRWYþ
	WXUTTVX[WTþXX VQ
¡UTRTTþW[SQUWUXUURRRTþV_QU\X¡WRRUQTT¡þ]TVWO¤VURVRUZþUYVWX_¤PSVWXV
RV
ZþX	WYY]£S
XVX	XZU^I^þXWWO¤V¢WW\X	VV^]\þV[QQU¤YYW_^T[¤\\_þüUZY¤Y [¤Z¢[¤\\\þUUWVWXU¤£Q¢[¤\\þXZ WSWQ¤[X[¢VY[¤Z[þVXXWWXYP^¤PX
OW]þYV XZVYZP¤WVOQ]þX	W XUYZUW£¤_QV	[]IþVW£WVUZUü[£QSVZX^¤þ	YUXVW ¢V¤¢XUV0V]^þ\WYZ £W£TUVXXX]^þ¢OUVTV¡\££XX[VU]H]þP££WYV[O££VZYXZ]ZþVQYU\Q]^UXWZ^[\þV¤\TTQ]\VV¢Z¢þ¢W¡YSXUWQTZUY^[þ ¢VUXV¡ZWVXS£VVú\^þ£VYW¡WUWZ¤WWú\^þX	¢X¡WXW¤	U]]þYW	¢WVU¤ü_\]Hþ	U	U¡¤^¡\^þ[£P[]þ¢S	^ÿþTRRTþRVURQRRþV
TRTPQRWYþ
	WXUTTVX[WTþX VQ
¡UTRTTþRZVUWUXUURRRTþWY£O[WZX¡WRRUQTT¡þZRVüV
WUVURVRUZþüàUQ	YXWVWXV
RV
ZþRVWTVV\\
WXZU^I^þWYZWVWVQ]
	VVV^]\þVüWV	¢QPV[XXV\\_þYW¤YUWX¤WUTT_\V\\\þWRU WY£Y
V£UW\\þWYXü¡X
^OWYVWZ[þRUWXZQUWZ_Z\\
UU]þVVXRUX	TTV¤Z_VUT]þVU^
VX	ZVQRPP[[VW[]IþW¢PRUUW[WX	UàT £^¤þWXU¢VWXWWü\W	XWWW]^þW VWWZ WTV^üYV]^þ[XYYXVYW YTTW[VW]H]þZZWUYXVX¡URàWX]ZþUUüYV[ZWWX  VW
^[\þ¡ XRVV[YXXW UVY¢Z¢þ[¡XUVWVY¤\[XWXWUY^[þ^	WWXXVRV_[WZYXú\^þ^YVYVVT[üWú\^þWYWU
¢QQPTV]]þXWYUXXYW\]HþTV	YYXW\^þW^XU[]þVXW^ÿþRST þVURRRSSXþ
USTRRSWYXþ TTSVX[WSWþYW VVV¡USRTTUþ W VñVUXUURRS0UþZUY 	ñXBWSSURTT¡ZþSY		VUXVUSVSRUZZþUXW	WWUñV
RV
ZIþVTXXBW
	WñZU^I^HþXXVUX£HVX	WVW^]\]þXVVW£VV	ZXV\\_]þXVVWW££VZX	V\\\]þXVW£W¡ VXYV\\\þX	U	B£WV W	YWXZ[\þW
WVYZB XZWTW	TT]]þ0X[WXVZTZY£¡WTS]]þSRU0ZWVVT¢ ¢£¡	 []I\þVSSRZWWU ZWB¢ B^¤þ	 ¢XUTZ[¡
WVZV ¡]^Hþ¡T	¡¢T\\YW	VUWV]^]þW Y¢¢¢URXZ]W	V]H]]þó¡¢¢X¢¢ ¡T Z][Y]ZþW	BBXXWV ¢UT Y^^[\Yþ¢
£BVX¢W¢	¢UT¡¢Z¢þBXRX¡	V
UWX	¢	XSY^[þY	V	XUWXZX[UVú\^þ	YVSVUUVX[UVú\^þYUU
UVVWV]]_þVXYUW	ðYU\]H]þYYVWVW\^]þY	V[]þVV^]ÿþRST þVURRRSSXþ
USTRRSWYXþ TTSVX[WS®þYW VVV¡US®TTUþ W VñV¯¯®URRS0UþZUY 	¯_­¯SSURTT¡ZþSY_	¯¯¯XVUSVSRUZZþUXW­¯_­¯Uñ_V
RV
ZIþVTX¯¯¯¯¯¯¯ñZU^I^HþXXVU¯¯¯¯¯_	WVW^]\]þ­¯¯¯¯¯¯¯	ZXV\\_]þ¯_­¯¯¯¯_ZX	V\\\]þX_¯¯¯¯¯¯_VXYV\\\þX	_¯¯¯¯¯_W	YWXZ[\þW
WVY¯¯¯¯¯WTW	_T]]þ0X[WX¯¯¯¯¯_¡W¯S]]þSRU0__­®¯¯¯¯¯¡	 []I\þVSS¯¯¯¯¯¯¯_B¢ B^¤þ	 ¢X­¯¯¯¯¯_VZV ¡]^Hþ¡T	_­¯¯¯¯_	VUWV]^]þW_Y¢_¯¯¯¯¯_W	V]H]]þó¡¢¢_¯¯¯¯¯¯Z][Y]Zþ¯_BB¯¯¯¯¯¯¯_ Y^^[\Yþ¢¯¯¯_­¯¯¯¯¯¯UT¡¢Z¢þBXR­¯¯¯¯¯¯¯¯¯¯_SY^[þ__¯¯¯¯¯­ZX_¯¯ú\^þ¯¯¯¯¯_UVX[UVú\^þ¯¯¯
UVVWV]]_þ¯YUW	ðYU\]H]þYVWVW\^]þY	V[]þVV^]ÿþ XWVþ\WWVVVYZþ\][WVVXWY
þ[W[_\ZWXX þYXXVWY¡ZZZ []þY0WVVYY\YZñZ [ þZ¡XXVYWW[B\ñ	 ]Y^þZZUVWZWYZ\YZ		]WþIZYZV
ZñY[[	[\YþH^I[Y^ñ[	
[B\\XZþ]\]\[Z[	\ZH£\YZ\\þ]_\YZ\^	ZZ£[ZZ\þ]\\
Z	\^Z££[[ZZ\þ\\\ZZ]\Z ¡[£[Z\þ\[Z\[]	[ Z[£B	Y	\þ]]ZXX	[X[^\ B^]Z[
[þ]] WX[¡£]^X^Z\[_\0þ\I]  	¡£¢ ¢XZZ[^0YVWþ¤^^B ¢B[^ Y[[^VWWZþH^]]¡ Z^Z[
¡_^XY\¢ 	þ]^]¢Z[YZ	[]\\X¢¡	X¡þ]]H Z	[]^\VY¢¢¢] [þZ]
]_]^ X¡ ¢¢\¢¢¡óþY\[^^] XY¢ Z[\\BB	[þ¢Z¢¡XY¢	¢[¢\ZB£
¢þ[^]W\	¢	\[Y
Z	¡\V\Bþ^\úZY_\^\[Y\	Z	]þ^\ZZY_\ZYYZWZ]	þ_]][Z[ZZY
YY]Nþ]H]YY]ð	[Y]\ZþNþ]^\Y[Z[Z]]þLþ]ZZ	]NþMþ]YZZþKOÿþXVVXþVVUVYZVþ][VUTXVX
ZþX[_\ZXXY\[	
þXXVXY¡
UZ \þXVVVYY\Y[YZ^Vþ¡XXUYVV[¡\^[_O£][þZUVZVYZY[
ZüZV^þZ
ZV
Z\[Z[\]	UYàüþ^I^Y^\[
\\ZZX[ZVþ\]^ZZZ	
]UZ[Z[^][þ_\\Z\\_ZTU¢	Z[üZþ\\\Z\_XXY[¤\[Y]¤[]þ\\[Y£Z
]£][ YV[þ[Z[Z][O^
\¡ü\][þ]YY
\\^_^[YU^\[YVþ]XYZ_^¤ZXX	\YV\ZZþI][[Z__TTVUZ^	\Z
^YZþ¤^£ XàY	\[_[YYVT¢[þ^][[[\	[\ü[[\[Z¢Y\[þ^]Z]ü^ZX[ ^[[Z [þ]H][Z_[XX] []Z\]]\_þZ]\[àVY¡\Z\]Y[^^þ\[^
[Z  \[[^_Z]üYYþ¢Z¢]ZY [\\]_ZZV\ ¡þ[^YY[\[\_\¤]Z[ZY\¡_þ^\ú\]^[__ZVZ\\[[	^þ^\ú[ü_XZZ]Z]^þ]]ZXTUU¢
Y[][þH]\[]\\Y][\þ^\[\]]	ZXþ][Y\^[þ^[\ZÿþXVVXþVVUVYZVþ][VUTXVX
ZþX[_\ZXXY\[	
þXXVXY¡
UZ \\þXVVVYY\Y[YUW_[þ¡XXUYVV[¡\\YU_ZþZUVZVYZ¤O[ZX]þZ
ZV
Z\[ZWT¤_\[Z]Yþ^I^Y^\	\Z\
W£]]][	\þ\]^ZZ	\\[[¢Z¤O[[\þ_\\¤_X^_[]]¤YUU_Zþ\\\¤_¢^¤_ ]¤]^Yüþ\\¤_¢U£¤Y\[Z[YYþ[Z¤_]Z¢_\_¤U[W[ ^\þ][O
\T¤^T]\[[\\Zþ]UOZ[¤T^]Z^\ Z]þI][	ZU_¤£[Y^]Y\ [	\þ¤^\^ZWU£_üY^YZ[£[Zþ^]Z0ZY\¢¤Z¢ [Z\Y]	þ^]\\\ZYX£[£ ^][\þ]H]YZ_\\££\¡ZXZYO¢þZ]^\]^Z££O_Z][££Tþ\[^^[\Y^]U\Y]UZþ¢Z¢ZZ\]UXX\¤Zþ[^YY^XU[Y\W]¡[¢þ^\úZZ£W\Z[^¡Z\YZ¢ þ^\ú[[¤^[Y[¡[]Z£þ]]Y	¤[\[¡\¢	\þH]\_ü¤YZ[¢	[]þ^\¡^¤¡Y	Y	þ][T£_þ^	W¢ÿþ0XV þX XVVXVYþX£WWVVUYZ\þZ\][WVUX[Z^[þZ[X[_\ZXZY]Y	þ[YXXVXY¡][Z	\_þUYXWWWYYYZ][\_UþUZ¡0XVYWYZ[]][_^^ZYþZUUWZZ\	Y
\[¤UWZþZ
ZY\\W[^\^Z_^Y[[þ^I^Z]]\XZ]¢_[\¤[Z[þ\]^[ ^Y\X£Z[¢UVW\	þ_\\[[\[[\]Z¢_\YW[Zþ\\\Z^^\]V[[Y\]\_¢þ\\ZZY]UY]^^]\üVþ[ZZZWUVVYZ[]V	\£WZþ]ZZ
\Z]^[]^XVZ\þ]Z[[]__]]\ZZZ^\YZþI][Z\¢]XUû^W\]YVYY\þ¤^¢¢]^YV^^\[[[W[ ^þ^]¢\[\[\ZYV[[Z]\\
þ^]£\üV\Y[^[]\^]Z^üþ]H]^^¢Y^\Z[[_Y^]ZüVþZ]\WV]ZZY\_\Y^Y]££þ\[^[[Y0ZY]üZ[ 
£\þ¢Z¢£[\\\[[\[£ ^Y[Zþ[^Y0[Y[^^^W\\¡]^þ^\ú [\_YY£YZY]üþ^\ú\Z]X\Y^Y\þ]]\\ZZ	]^WY	þH]\[ZY^	\Yþ^\Z\ZZZþ[[	[ÿþ XWVþ\WWVVVYZþ\][WVVXWY
þ®W[_\ZWXX þYXX®WY¡ZZZ []þY0WVVY_¯¯ZñZ [ þZ¡XXVYWW¯­_¯	 ]Y^þZZUVWZWYZ\¯¯¯	_]WþIZ
ZV
Z_ñY¯­_¯­[\YþH^I^Y^ñ¯¯¯¯¯¯¯\XZþ]\]^[Z[	_¯¯¯¯¯YZ\\þ]_\\Z\^	¯¯¯¯¯¯¯­þ]\\\Z	\^_¯¯¯¯­_¯þ\\\Z]\Z_¯¯¯¯¯¯_\þ\[Z\[]	[_¯¯¯¯¯_	\þ]]X_	[X[¯¯¯¯¯]Z[
[þ]]W¯[¡_¯¯¯¯¯\[_\0þ\I][ 	¡¯¯¯¯¯®­__0YVWþ¤^B ¢B_¯¯¯¯¯¯¯WWZþH^]¡ Z^Z_¯¯¯¯¯­\¢ 	þ]^]Z[YZ	_¯¯¯¯­_	X¡þ]]H]Z	[_¯¯¯¯¯_¢]_[þZ]]_]^¯¯¯¯¯¯_¢¢¡óþY\[^^] _¯¯¯¯¯¯¯BB_¯þ¢Z¢¡XY¯¯¯¯¯¯­_¯¯¯¢þ[^YW_¯¯¯¯¯¯¯¯¯¯­V\Bþ^\ú¯¯_\^­¯¯¯¯¯__þ^\úZY_\ZY_¯¯¯¯¯þ_]]Z[ZZY
¯¯¯þ]H]\Y]ð	[Y]¯þ]^\[Z[Z]þ][Z	]þ]^ZZÿþ£V£¢þW£¥[I\£VþW£VUDEON^¨§þ¤WXWWUU]^Hª]Y¨§\þZZ¢UVUVU¥ªY2XXUU_§£Yþ
[§§¦U¢UUXX]ZVUUUWWUWW¦¦FþV¢UW_ª§[[XW¥WUVUZUUWVWUYHFF¦þUWYUUUVZY[GF¤E§WWWVUVUUUUH©ª]X©¤W¥]¨ON\WUUUEHUEJ^UU\£MMZMVUZGUU\¨«^UUUU	V¤£F_H©^J_WWZZJMWZZLEVWH¦¨ZDU¢ü§¦H[¨^ZXXU[[^©M__¨¨WWVUHJ¨¦EIM\¤UUEG¨§§J\N2Z¨M^J^XWUWG2Iª¦§©XWVUWVW]KMNM^©^]L_YU¢WYHJYª_WWUUUUWZLGHLJ^\¨_]^\§«\WVUWU^_HWUUXX	GKJ2\_N¨ª^]þ¨§^XXH£W[§WZWUDNNNM_M_^^\«©üþI©_^^[XUG¨[WML¤¢FNMMMJ_N_þK§L22E
EH_UGMJEJ_^^^©­1MNNþO¨EHIG2]HH^[Z£G^§\\^]INKM­^þ¨OJ]§EGG¨_\

¤M^§§ü_GNML­üþ¨MW¨_HL©Z]HFM^N§§KLNJü­þ¨GGW¨ONMM]

ü^N^H2FN©^«\_þ¨¯1
§MOKJMLX_XªF^N¨¨MLN©\EþOþ¨HGV¤JLN¨_IW_
J3FN©©\LJZ3þNþO¨3I^33N§]HY_NJ_INK__Z\KHEGONþN©MþY^MN¨U££^N¨ªJK^¢
^KGKHNþNG^UU[GK_JUUUN§«]HHYü[H3NIþK2MO
UWUEJ©E\VUNN«]L^^\[X
_KNNNFIOOVWW¢[§O1W	NIEHN©L
U^]«\þN3þOOZW¢U
K¨UH[\N¨3GN©LM	G©_«^þNOJOþM[[JKWUUUN_MMZJ\_N]FONþNþ ¢ ¢KL]V¢UMZZZN]^^¥¦LHKþVYUUUM_	¢	NN^[N_^¥WYYMþ
ZVUUL3¥_NN\^N§W	¦þ¢_›^2UM§N]^N^þ¨¤H
^X§N[GNMþX
±V^^þXV[ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYZþYW0² TUVUZYVX	]þ[XUUXU RUVXZXUUWVY\£þ
XXVT±UZV 0SWUVVY ’’¢U
þV± U±SVSUWTUSW“ W0V V¡WUWþ	UV±±U T±UU±WW¡XWVUT¢XUXY\þVWUSRS±WV±TS¡¢VTVWU SX[^]þUBUXV±°USVWW± ¢0SVX[[\]þW¡_[VUUS°±UW UXVVW\þVV_’’	XUURT0¢[ X\]^¦\ü\þV _RR°“][SV²°	V[I_\WYX\þXY_UYW°’\V
Z^\WZ_]þTW_W__WWTU¤YU^H^Z[]]üü]_\ùþSW_X_°°¤

¦VWZ^]HWWü\\_þ X_W_WUWW^VF\_]]Xü\üúZþB
_W¦  £¤W_V[\_\^^û^[þV_X¤R£¢¥_WX\_\_¢\þV¡ ZVR“^W_TT
ü\ü\	\][^þUYVS\£ ’W^Sü\\[Z]]þWX[XWS¡¢_	 []L\^[ü^üû\þVWü“¡\Y°F^BB
^^Xü£B_ù^þVXSR¡Y
VU ¡[]^]^]¥W		^_]þXX^  R¡W	V[¥^£W	¥[\þTYR__XURZZY_]¢V^ü[üþSW_°°£	 XUX[£Z_W¡Zü\þ X^W_	TYW\VWY[^	^[Z]]þB
^U¦¡SU¥ZWV	]ü^¥^[_ù\þ¡Y_T£R¤W¦	\UVZ]ûù_]\ ¦
_ùþVB¥’[WR ^X^WXF\ûü\WF¢¦^þV ¢ YU¢^ \û\¥ü£¥^þVYUS X£^ 
\\^£V
^þ
ZVUSU[\U \[]\¢W	
\þ¢U	USRBXXY\\]þYXX
¡X\[\]þX
±V^^þXV[ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYþYW0² TUVUZYVXþ[XUUXU RU
WTXSRXþXXVT±UZVRRR TV\^þV± U±SVSU_XTT±TRX]üþ
	UV±±U T±U[  \[±W[_üOþ	VWUSRS±WVV± ¡VY\£Z]^þUBUXV±°U[S£££¢YR[	R^¢þW¡_[VUUSVSRX [UVB¡		_^Y]þVV_’’	XUUR±WW SS W\^^^[¢^þV _RR°“][SV±WR0 RS^^]^^
TþXY_UYW°’\VYSZ¢^_^^^Z
þTW_W__WWTU¤YU^UY±Z__^^VZ^þSW_X_°°¤

¦VWZ^YWZ__^\	Z]þ X^W_	TYW\VWY[WT^^[Z\þB
^U¦¡SU¥ZWV	]üW_]	]^\\þ¡Y_T£R¤W¦	\UVZ]ûù__]Y^^\þVB¥’[WR ^X^WXF\û]^\_ü^_]þV ¢ YU¢^ \û\[Y]üþVYUS X£^ 
\\^£V
^þ
ZVUSU[\U \[]\¢W	
\þ¢U	USRBXXY\\]þYXX
¡X\[\]þX
±V^^þXV[ÿþ¤¢ZZþ[¤¡XV¡XZþYWVY
V[SXYZþYW0² TUVUZYVX	]þ[XUUXU RUVXZXUUWVY\£þ
XXVT±UZV 0SWUVVY ’’¢U
þV± U±SVSUWTUSW“ W0V V¡WUWþ	UV±±U T±UU±WW¡XWVUT¢XUXY\þVWUSRS±WV±TS¡¢VTVWU SX[^]þUBUXV±°USVWW± ¢0SVX[[\]þW¡_[VUUS°±UW UXVVW\þVV_’’	XUURT0¢[ X\]^¦\ü\þV _RR°“][SV²°	V[I_\WYX\þXY_UYW°’\V
Z^\WZ_]þTW_W__WWTU¤YU^H^Z[]]üü]_\ùþSW_X_°°¤

¦VWZ^]HWWü\\_þ X_W_WUWW^VF\_]]Xü\üúZþB
_W¦  £¤W_V[\_\^^û^[þV_X¤R£¢¥_WX\_\_¢\þV¡ ZVR“^W_TT
ü\ü\	\][^þUYVS\£ ’W^Sü\\[Z]]þWX[XWS¡¢_	 []L\^[ü^üû\þVWü“¡\Y°F^BB
^^Xü£B_ù^þVXSR¡Y
VU ¡[]^]^]¥W		^_]þ£XX^  R¡W	V[¥^£W	¥[\Uþ£S YR__XURZZY_]¢V^ü[UWUþVWXU V_°°£	 XUX[£Z_W¡ZSY^\\V VZTSSA	TYW\VWY[^	^[VU[\^\[¢WY£ BWSSSU¥ZWV	]üXV	WZ\]]]\V W¡YWVBVRS	\UVZ]ûùVY[]^^]_[_W\YWWWXV£XVVS WXF\S 
Y][]\]\^þ__¤¢XU¢W  £XUTTUX¢\\\_[\\^þ^^\WV CTWWU SSY[^\\^]^\\þ^WW\£WWX¡£U[]^]^]þ
^XZ¢XT£¤ ¢¤_
\^[]
üþ^	ZX¡U£Y\]__þ^Z[WZ
X^__þ^^\
[[_üþ^_üÿþZ[£ þZYWUY	UþZ^XTUS UUVUZþZZXT
TST¡TWZ
WþZ£[W	TS°STZWW	[þZWWTWU  X	XS°°	[Z[þ
ZWVVTñXUBWU	WV
	
[^þ	£WUUTUXZWYZYXT[	[[]óþXUWS SXZDW\[_	UX°U]
þSVU°X[UV[Z]X\Z^UWT\\\\þV	W^Z[Y^\\S	]	_ZSX]_\^\ZþWW¡VVUXS^^	°V¢
S[X°S¢V ¤]¢þ\[XX¢W []I UU^VB¡	X_\]^]þ
ZWYTU[US
S TU¤[_^[]]þ
U£ °U U[^^[\^\^ûþ
ü
£ US	_^[^^þ\WX¢\S^_OZ]þ
ZW^_þþÿ þVS
UTWUVVVVT 	SV T  þU¢ YSV TWSDVVUUTUðþTVW WVVUñTUUTUVUUWVU	UUþ
UVVUVUUUöTTX¡UX VðþUUTUUUUXUUñVñVTWþUVT UUUñVWþñW[VWWWþWU ÿþ XWVþ\WWVVVYZþ\][WVVXWY
þ®W[_\ZWXX þYXX®WY¡ZZZ []þY0WVVY_¯¯ZñZ [ þZ¡XXVYWW¯­_¯	 ]Y^þZZUVWZWYZ\¯¯¯	_]WþIZ
ZV
Z_ñY¯­_¯­[\YþH^I^Y^ñ¯¯¯¯¯¯¯\XZþ]\]^[Z[	_¯¯¯¯¯YZ\\þ]_\\Z\^	¯¯¯¯¯¯¯­þ]\\\Z	\^_¯¯¯¯­_¯þ\\\Z]\Z_¯¯¯¯¯¯_\þ\[Z\[]	[_¯¯¯¯¯_	\þ]]X_	[X[¯¯¯¯¯]Z[
[þ]]W¯[¡_¯¯¯¯¯\[_\0þ\I][ 	¡¯¯¯¯¯®­__0YVWþ¤^B ¢B_¯¯¯¯¯¯¯WWZþH^]¡ Z^Z_¯¯¯¯¯­\¢ 	þ]^]Z[YZ	_¯¯¯¯­_	X¡þ]]H]Z	[_¯¯¯¯¯_¢]_[þZ]]_]^¯¯¯¯¯¯_¢¢¡óþY\[^^] _¯¯¯¯¯¯¯BB_¯þ¢Z¢¡XY¯¯¯¯¯¯­_¯¯¯¢þ[^YW_¯¯¯¯¯¯¯¯¯¯­V\Bþ^\ú¯¯_\^­¯¯¯¯¯__þ^\úZY_\ZY_¯¯¯¯¯þ_]]Z[ZZY
¯¯¯þ]H]\Y]ð	[Y]¯þ]^\[Z[Z]þ][Z	]þ]^ZZÿþTX
 þ£UWYTVWWþAYD£¡¡	¡A¢þ£YA¤DV VVW 
VUCþTVWT¤ U	X]ðW VV	WVþ
¢ X¡WU ¡¢“¢“	X]ðWY	XX¢¢þ£ UUWU T¢ “X¡W¢ ¢“ C WU X£þ][Z]]Z\]Z^Z\]]IZZ[ZZ_Z^þ^[]I\\]H\]]\]^]ùZþ^¤\HH]]]\\[\þ
H]^\]^[^þ\]^]Zù[^]þ]^^]]]]^þ]^^[\þ^^\[ÿþH]^]þ\\^]_\^þ_]_\^]þ\\^]ùZ^Iúþ\Y\]^]\ü^]]þ
[\]_^ù[\\H]^þ]]]\]^^H]]]]\^]_\þ][]]\]\^\]]I[[]_\^þ^[]I\\]H\]]\]^]ùZþ^¤\HH]]]\\[\þ
H]^\]^[^þ\]^]Zù[^]þ]^^]]]]^þ]^^[\þ^^\[ÿþH]^]þ\\^]_\^þ_]_\^]þ\\^]ùZ^Iúþ\Y\]^]\ü^]]þ
[\]_^ù[\\H]^þ]Z]\]Z^Z^ZH]Z]Z]Z\^]ZZþ 
  X WUUVU	UUWU“X¢VC	 XUUXZ	Uþ
XXUWW WUUW XXXYX		þU XU	UVWXYX
 U¢¢WUXU	Xþ
W ZVW 	UXU	X	WòXTYXþ YUD[TXXYX	ôX	þ¤V
	\W CX
YVþXV£¢	 YGþWXYYÿþJYþKJõJþLøJKJIYþJIVWLM
õK
öþJHI6WYTHHGKõJIYþKY£¡MI[IKLKK
JIþøKöIGWX HULLKöøKYþL÷
K
YIG V
GTLø
LK	Iþ	I£¡ LKKKY\HñYWXU£MKKKþ5¡HUIWKKøõ÷öYI¡¡WSYJLLLþK	UWUW¡JK
K
J	 YUJ6I[þLK
YVSUGGHMLLJJYIN¯JþLLKKJI IJHMøKJ
YMN¯KþI¤£B¢øöôK¡W¡[ILHGLK
Nû¯þIIHWGHKLMJL÷KöZWSUSYKKM\ý[þ[Y¡ JXT¡FKHLJJZSVñ	WJLù[^þLKööGW JK£¢IøKJKLYU6XVL]^þM
÷ööYUNVVT¢£¡

J[^^¯[þGI¢TKLK÷÷[KKTWVTUWøN¯[¯KNJ W¤RUHIWøø÷KGYVRS ¡IS\¯MN¯¯¯Lþ UIIUUL0M	YUIITIûNNOý]þKKH2¡SUWJMMõYWULN¯ýþ	J4I¡VGGMUMøö

MNNý¯þG6TIHHJLøNN_þIJSSYTZSLL¯\þH5U ¡II\þI¢RWÿþJYþJõJþøøK
JYþIWVWML
KKJöþ77HXWYHTXLKõöJYþJY£I IJKIJ

JIþø[öJVWI 	KJGöøöYþ÷

[WH I
IIWø
øL	Yþ
£¡ 
YK[\IJYKHLHøKL[þ¢¡W7YLFXøõ÷öJ¡¡WSU W\LþJJ	HWUJK V
KJJ[	 YGUTUT[þLK
VSUGHHJIL÷IH3ñûýþMLKIK£¢¢JKLNNøK
JLNNýþ¤£B¢LKöJ[¡W¡IIHIKL

N\ýþTYYV£TV÷L÷
öHIMUIYJMT\¯^[þ[Y[IHXT¡JVKM
IJVHIIGGHùN^þJööJYW 0V£¢£øJILYIHXMLHý¯^þ
÷ööIHJIKT¢£KJ

[ù^G¯ML[þ666TWLGI[YUHLWIHUM
GKN¯MN^IJ¤RU0LLIø÷÷[HKKJSK¡	S\¯¯KMN¯¯[KV U¢ KIS0ö	YG3HXTVûNIN¯¯Nû\XRRSKUI¡SUWøJùõYHUû¯LMG¯MLLM]USSRJH[WWVUøö

NNüý¯¯KK^^JX ¢KU 	UWTVHVñøMM¯¯NOûL¯NMJJKLMKJW\\ SIITZSU¯\NKI]MN_JJW KúV
]\KIUTU ¡WU\û¯NMKMû]VV	¡¢¢U^^]¢ ¡T¢	RW\¯ýIJHN¯ý]úúW	BBKLWV ¢UNû¯¯]GLGMOû^\JW¢VBBV^KWW¢	X°¯[\HG¯ýýNLüT	XIXLVZ^_
UKX[¯ú\^G¯ýNû]ûN\V ZIX
¡JKVWYXXûýMY[ýû^LVYJJIIJ^_£UUK£UT¯¯ùJJMNN¯¯LþYZW V
^LVWV X	û¯NNLJN¯^þLLXU[^KXñù	ýLû¯\]Nûþ
L^V
XYJMBú\ý]^¯^þLLYX	V
¡\ý¯^þ\\X
°û¯¯þ_Vý]þLÿþV þWK	HYþ
WL	WXUYþJIVJFJKV¡WþMJJJ£KVXXWXU¡ þZVIJLVXKVVWUVþJXVLHVVXHJIV	¢K¢þY	WKVWWVXFJXSJ	¢	XüUþ	J	WIWHX 	KJGIWVI[XZILYþSWWJ£GJKFVW
L¢ VJ[KVKO]þ4	¡£¢KJWIXW¢ úT¡LJKJMMþWK HBKIKUJ¡	T¡Y WUûJJN]þJXU¡ VZGIIJ¢¢Y W¢¡óLVV[NNþTIIIWKVK¢ VGKJ¡óB	WV	ýNNþIKXV	II¢WHBHKWY WVVý\þXULXSX	¢HMWUJB£LJ¢¡óXûû]û^þ	XVKHKILXZJWUX¡XRXLHWTNûNùý[þIVHJVI JUIIKKUKS	IYGG¢N^ûN]]JIJ¢ IJ¡VWVJJIIUU	YYIIK][\LLJKJY WUYJJKUYKK	W	¡LN]ýû^\û]þKKW¢¡LIIJVIYYVUXW¢ Y[\û]þóJJWV	YMHJVWWVû[ûNûIþ	J WVVULY¢VX XüûNû\þXXL¢£ UU£
Mü\þKL X VKVZM]¯þ	VñX NþXM]ÿþV þWI	Yþ
WB	WXUYþVH£XTV¡WþZ	VV£UVXXWXI þZV££VVXTVVWUVþXV ¡VVIIIXXV	¢	¢þY	W VWKKOXU	XSX	J	XOUþJK	WTWZX 	LJXVWVUJXZILYþMWI¡£YZTYIF[J¢ VU[XVUû]þIH	¡£¢ ¢TVXJ¢ 	Y¡VKII[þJK ¢BWZ UWL	W¡Y WUNJJû]]þXU¡ JMLHL ¢MY W¢¡óWV[]IþTIVVWIV	¢HILGKGKB	WV	\þVXJVK¢	¢WKBKIY WVVY¯\ûþXULGJXI¢JXWU
BY
KJJóXX[Mýû^þ	XVIIHKJZXWUXJXRKHIWTûù[þJW
V¢VKJJIUUVS	JYHHJ[^]]þXJ¢ 	TIVIYKHJ
UI	YLYXIILMIýW¡	T¡Y WJYð	YKKXV	W	¡Y]JIN¯û¡VYKW¢¡óWVWVHJVUXW¢ û[û\I¯ýN]\XJKLJ	WV	JIJWVWUJVN[\LKI[^]]KSSR WVFDWY¢VJ XVZNHKýûý^VX ¢XU 	XIYH£ UL£
ýýýü\	K\\U ¡T	¡XW\M£ X LWVZXVHý\]^_LXW Y¢V
IKJ°	VñX ýNN¯LJ]^[]VV	¡¢JU^J]¢ ¡TX]¯\Y¯GH]\ý]VVW	BBW\KWV ¢Uû¡û¯¯N]\ý
û\XW¢VBBV^MHWW¢	X¯[LKN¯ý¯¯û[üT	XKX¡ZJJIUWX[ýú\^]NM¯]û\V ZWXJ¡JLXVIYX[N¯úû¯ûûWKY XKV^_NUU £Uûûý¯K^V]N¯ýþYZW JJ^\VWV Xý¯N¯MüNNM^þù[KKJ^^JñV	¯NLN¯LNNMþ
KJJLV
XYBLN¯^þLLMYX	V
¡M¯^þLMJ\J
°¯þLLJû¯]þZÿþKû]JþNMõJþýûNNøøþö
¯õûK
[Z[þ]JöõýL\JG]4\GCþIJNNYC J I£]KþNNMMNKYYH I[ZJöNøþN	NM
ø[X\
Z ¡[û
I
N÷þNLNJIL\[]ñKûûKJJ6I¡£þ
N\[ HH¡¡Mü÷IH\IZY[¡¢þ4TIIG ¯IHHLLGG¡HI[YNþ¢¢Tñ6JONJûM]IMHIJWNNKLþBKL[
K¯JMKJM¢HENKMLþBYöû
K]G 	¡[KMJGûNK¢BH¤þXYMGKñNHYG[^ONL¯LEGHIHIHXþYK	HL[	ñXZKû
HKKK¡XHZIJN_þY KWJHV\YYLNHLJ£HH []NNöþ¢¢VWKM¢J


HIHXZHIY]ööNNþ DVILBVW]øü[YXJ[XGJNMNKIX¢ þ ZHXH¡V û\W	¡JGZN÷Mø[Y0YVHG ¡KLXZVW£IIII]K¯NN]WHLMIILMNXIRJJ
LWV[][KMFNIJJLM[LHI_MN]UKGSR[ILñV	ûJ¯IJI]Z¡5KMF¯¯HKX KXJMJEXNMüLJHMWIH[YLJNU ¡LK¡XW\\	KJWIIFKHKNû¯K\]^_WXW HGV
K\U°HK
¡ ]HJ	¯¯I^û\]VVJI¢IJIL]¢KITWV]¢Iüýû¯G\\¯KVVIIIHJMKWVK¢U0¡K¯û]L¯Lüû\XJHMIMMK^XWHH	N¯¯K\û¯GJû_LJJI°KLLGL_
ILXM¯úGL]]¯¯NGý]N]KVKZWX
¡KJKJGWY\üKMN¯¯LHý^KLVY KKVIG_ùKM £UJ¯¯N\ù¯MþMYZW K
JMVLJJK	W¯LI¯L^üNý^þ[XU[JLJXñK	¯M\I¯L][¯¯þ
WK^V
XJJüBHNý]^¯ý^þLLüIYXKV
Mû¯^þLKK
°NMý¯þ_JN]þZÿþþûþn]JþJþKûJþKþ
¯øûJNøþû
¯LIK
[Z[þ]JGJIL\XX][I^CþüþIJKJGYC [IIJ]KþMHJILYII \[ZNN_øþ]MGHK[X\
HF¡[NN
H÷þNMJ£M\IIñIGNKûûMHK ¡£þ
L\IHHHLMLûJN_[IY[¢þ[[YXY4KHKJMFL¡[Y[Yþ¢¢T]]ûKII]\YJINLþJBXR[]¯LGI ¢IGGKNLþKBYYûNLKK46MJEFIK¯GIJ¢G¤þXKNN\MFJ]IYWJK÷KZX£Z[[XþH¡	W	IJ	ñXZWNKKZ JX\I ¡]_þJIK¢LKSV\YYNMûIK¢£II [ûûöþJK¢MGK ¢^NNûNMKHFLXZZIFö÷
þJ DLJLJKMNN[HKZ[7Y]IGûûJI6¢ þ KWXKLIN[KKKI ]KKZ]÷KFKIII76¤[ þLVXJKLUVX\J¯NNöG6WYYIIY þLK
VJVGY[]NûøLLW[YVWþ
[LXñKJ_
NO¯HIII[ZG0þLLMJMûNøKJ[W6H[YþMLTûYYWX]WW þ	V
¡IYHYþ6WII¢ÿþ\þI\^\_þ]Z]KKJ^þ[][JJ\^þ\I][^]\^\\^\HþH\¤^]\\ûL]þ^]H^]LL^[ú_LH]þ]û\^]^]L[\]ù^\\þ
]]\KKHLK
^[]^]KY\þ	Y\MI]N\FLL¤^ù^_]\[þ
LLLI]ù^\úJJ^\^^]\]]þJKY\_]]LI^\ü\]]þKLRý]ûKKL\üJJJKLHN\\KK[þJY\_]^\]û]LH]HûH\J¤^]þY_][[IKH\^ûH^]û
Lþ¡	W	Yù]û]KJ]]\^]L[LþY ¢WXS\[GG\\]]]ILL
^þ¢¢VWUJJ^[^GLK]üI]^\H\K¤þ MVXXKOW\]^[IJJFLI]^\úK^^þ JWX
üJKüZKOHJ]]MJK\_JKJLNM¡KLXZVWJKI[[ü\^^HI^]H\\LNLûûûXKRRJV
VLK ^]JJN^JJKK^\L¯Yû]JLKSKR[XJVý\KN\JN]N¯Ný^LLM¢KK 	FHUZ]I^KIMûN¯¯\ûII¡LLKXW\\ITYYû^üHVûûMLKWXWJY¢V
]\UH	VY^[üýG[ýû]^N\û]VV	¡¢¢U^^L¢H¡TKN¯KJý]\\ýý]JVW	BBW\WJM¢U0¢Z¯K]\¯ý
û\IW¢VBBV^XWW¢	û¯ü\J]ýý[üK	X°X¡VL^_
UWX[ý¯ú\^HLý\]û]\V ZWX
¡ XVWYX[¯¯ûY[ýNWVY XZV^_£UU £Uû\^V]¯ýýúþYZW V
^\VWV XMý^û	û]¯^þ[XU[^^Xñ	¯û\¯\NûW¯þ
WLLV
XYU	K\M¯Ný^þMIJJ	V
¡MN¯ý^þL\\XKLûNýþ_Ný¯]þZÿþIJ\þ\^KK_þZ][K^þKGK\KKK^þ\I][^KMLG\^\HþJHKKK]\ûJH\JJ]þI^]HK]
J^ûK_H]þ]\^]^]J[J\JIJLJþ
]]\KH\G^LKGIKLKY\þ	M\I]MKKFKK^JG^KK_\[þ
ZI]^\úHFIH^^MJK]þ¢¢Yü\_]]JJIL\LJþKXJ]H\\\JJJL\\I][þBLY\_û^\]FNJINJ\J¤^]þXYûû_][[KI]]\LKûH^
YþYL	W	Yù]^]IJI]]JN]ûL[þY ¢WXS\K[H\\KIL]IK\
^þ¢¢VWU ¢^[KK]IKI]^\LLL¤þ DVXXBVW\]LLùZ]ûLI]^\KJK^þ ZWKK¡V YLLI]]]û]^^]\_KJLNL^þVXZKJLUY[GLü\NJ^JK]HKK\Mþ V
VKLJ^MJ[\û^\J_]K\L]þ
MJKJV\K]N\LL][þMYUK]I^KNMKþ	TYYK^NLþ	VYLKOþLO]ÿþ\]L^þ7JLKNþA666=99J?ü?:þ£Y6666;G9;J>>::þH66T667:XJ:?K;E:	;=þ
KEE6H©IJ¢“JKMLJJ:YJJJ¢þ£ EE6I©©­ü“XL­ª;: ;G9: X£þ 
  677IMU©^^^:;¢VC	:I::UX¢	Uþ
67^^7767JJJ::=XXY::		þU^©U	U7FD7JJJJJ:J¢WUXOLXþ
^©ZV767:J:XJ97òXTYXþ Y779:;OYX	;;X	þJJKJªICX
YVþªJH6	 YGþ76YYÿþ\]L^þ7JLKNþA666=99J?ü?:þ£Y6666;G9;J>>::þH66T667:XJ:?K;E:	;=þ
KEE6H©IJ¢“JKMLJJ:YJJJ¢þ£ EE6I©©­ü“XL­ª;: ;G9: X£þ][677IM©^^^:;IZZ:I::_Z^þ^[67^^\7767JJJ::=]^]::Zþ^^©\H7FD7JJJJJ:J[\OLþ
^©]^767:J:J97[^þ\779:;O]Zù;;^]þJJKJªI]]]^þªJH6[\þ76\[ÿþHHIIþ\H7I^LI^þ_I67H^^K<:þ\J77656JM_^^ILOþ\YLLI67F79N7679<<LILJþ	[\]K7JJI7F¢FJKJH7]^þ]]]\©¬<J_LL876<IKNLJ^]_\þ][]]©^__^^6F79I7<O?¬_\^þ^[]I\©JKOMK76IFF6J>M_ùZþ^¤G^65HHHJIFI]F:NL77þ
H^J5FFFF;JIKKOMF6H]þ7:::MK]Zù[NF6FþNIJLI]]]]^Iþ]5F^[\þ^F\[ÿþHHIIþ\H7I^LI^þ_I67H^^K<:þ\J77656JM_^^ILOþ\YLLI67F79N7679<<LILJþ	[\]K7JJI7F¢FJKJH7]^þ]Z]\©¬<J_LL876<IKNLJ^]ZZþ 
  X W©^__^^6F79I7<O?¬UUXZ	Uþ
XX©JKOMK76IFF6J>M_X		þU XG^65HHHJIFI]F:NL77U	Xþ
W^J5FFFF;JIKKOMF6H]þ 7:D::MKYX	ôNF6Fþ¤NIJLI CX
YVIþX5F¢	 YGþWFYYÿ þVS
UTWUVVVVT 	SV T  þU¢ YSV IWSDN¨«VUUTUðþTVW WVVUñEGUTNNªUWVU	UUþ
UVVUVUO1öTNI¡UX VðþUUTU3UUHUMNIñVTWþUV2 UUUNVWþñW[VWWWþWU ÿþ3ST3þHIF2RHS­þJ_SEEESWYXþ _HLVX[EDNþYWOONMNUSRTMUþ WMOKJMLUURRE0NþZUJNOñMIWSSU3FN¡ZþSC3NN	VHXVN__INJUZZþUXWNNWWUñN¨ªRJHZIþVTFK__W
	N§«ZHHI^HþXXVEJ©EGVNN«VL^]\]þXVJLO1V	NIEN\JM]þXVVMW£HVNI3FN\LN]þNVWLJ¡ NN©INM\\\þX	U	KL­V WMNYWXN[\þW
WVYZM_XZWNNMTTN]]þHX[WXVL3GYMMNNSN]]þHRU0ZWVMC¢NM£N	 NKI\þHSSD2WWHMNWBN FNM¤þ	5¢GD2G[¡
WVZV EKL^Hþ¡T	KH§­\YW	VUWFMH^]þW Y¢MMRXZ]N	_NG]]þó¡¢¢XMNM¡TDL]I©NLZþW	BBXXWV ¢2T YHM[\Yþ¢
£BVXIW¢N¢UT¡_Z¢þBXRX¡	V3GWXN¢	XSY^[þY	V	M1WXZX[UVúD2þD2VSHUUVX[UVHD2GþKJGKþGUU
UVVWVIKH_þIIþKJOVXYU2NðYU\DN]þ	KKþIJLHþIYY2NWVWHDNGþ	IþGHIHþY	VIKþLMþVF^]þMGþGþLKÿþRST þVURRRSSXþ
ULKRRSWYXþEN§N^SVX[WSWþG§_VVI¡USRTTUþD§GFEUXGURRS0UþE¦MD23XB3SSURTT¡Zþ3MIHIF2UHNUSVSRUZZþI_OJ_EEE_­N
RV
ZIþK§_XX_HK§WMZU^I^GþG§GGXOOJ¦JNWVWN«\LþH§¯1W_NOKJMKXV\E_NþN¨HGWWJNOLN1X	V\3FNþN¨3I£C3IF§NHYN__INþX	M	B£WKI¨MNYWN¨ª[IþW
W_YZB FK_LMNTN§«]Gþ0XGFGVZT2J©EGNNN«]LþSRU­1WVVJL O1¡MNIEINþVI2FZWWFHZWH¢MNI2FNþ	 ¢XITZ[IKJVZV N©]INþ¡T	¡¢TNNKL­VUWN]^_þW ­¢¢¢NMXM_W	N]H]]þó¡¢¢X¢¢ ¡L3G][N]ZþW	BBXXWV ¢M1 Y2^[\Yþ¢
£BVX¢D2¢	HUT¡¢Z¢šþBNNX¡	VGD2G	¢	XNN^[¨þ2NY	V	XKHX­X[U2N¨^§þ
IKH2N2FYVSVUUVX[U2N2Fšþ
NþIþYUU
UVVW2]IJþ	HþLþVXYUW	ðY2\]HFþ	KþJþYYIVWVN\^]þIJþKIþIJNGG3G	N[]þNLþKKJGJþM1þVV^]þHÿþ XWVþ\WWVVVYZþ\][WVVKLY
þ[W[_\ZW^N§NEþYXXVWY¡IZZ_§GþU0WVVYG\YEFG§DþZ¡TXVYWW3B\32DM¦EþZZURWZWYNHY2FIHIM3þIZ
VV
N­_EEE_JO_IþG^I^U^M[§KH_\\_§KþL\«NWZ[NJ¦JOO\GG§GþN_E\V\KMJKON_[1¯§HþNF3\V	\1NLONJ[[GH¨NþNI__N]HN§FI3C£I3¨NþI[ª¨N[]NM¨IK[£B	M	\þG]«§NXNML_KF B^]_[
[þL]«NNNGE©J2X^ZGFG\0þNIEINM¡1O LJZZ[1­YVWþNF2INM¢H[^HF[[^F2IZþNI]©N Z^ZJKI_^XI\¢ 	þ_^]N[YZ­LKNNX¢¡	X¡þ]]H]N	[_M\MN¢¢¢­ [þZ]N_]G3L¡ ¢¢\¢¢¡óþY\[^2] 1M¢ Z[\\BB	[þš¢Z¢¡XYH	¢2D¢\ZB£
¢þ¨[^NN\	¢	G2DGZ	¡\NNBþ§^¨N2Y_\­\HK\	Z	]N2þšF2N2Y_\ZYYZWZ]F2NþJI]2[ZZY
YY]þIKLMNNMþ
FH]\2]ð	[Y]\ZþNþ
]^\NZ[ZI]]þ	LþOþ	][N	G3Gþ	JþMþ]^VZþ1MMMLNNþMMþNLþHþNOL¯JþK¯ÿþ3XW3þ­WHV2FIHþ\][WEEEW_JþNDE_\ZLH_ þYMXVWYNMNOO[]þN0EVVYYLMJKOM[ þZ¡NF3YWW[IMñONJY^þZZUJNI__NZ\HZ	NN3CWþIZHJVª¨NñY[[NN[\YþH^IHH^«§N	
[__KFXZþ]\]^LZ«NNZGE©JEZ\\þ]MJ\NEIN	Z1OLJZ\þ]NL\NF3INZH£[MZZ\þ\\\VNI©NN ¡JL[ZNþ\[V\[]NM[ Z­LK	Y	\þ]] XXMNN[^\_M^]Z[
[þ]] WNNMM]G3LZ\[_\Hþ\IKZ 	N£MN¢CMZ[^0YVHþ¤MYF NB[NMH[[2DWWHþH^L¢E Z^Z[
¡_G2DG¢5	þ]^HMF[YZ	[]\­§HK	X¡þ]]G
_	N]^\VMM¢] [þZLY©I]LDX¡MNM\¢¢¡óþY\[XH] X2¢ Z[\\BB	[þ¢Z¡¡XY¢N¢[I\ZB£
¢þ[^ W\	¢N\[G3Z	¡\V\Bþ2DZY_\^\[1M	Z	]LþG2DXZY_\ZYYHWZ2DþLþ_HKXZ[ZZY
YYGþOLþ]NDVY]ðN2Y]\ZOþMMKþGND	[Z[N2]]IþNJKNþKNþKVZ	]þJþOLþ]^FZþKþMKþNþLLNÿþKþIþIþKþHþGGJJFþFG6HIþGMHþHFHKNþNþHþ22Iþ	IJþJþ64Hþ
GHIDþ6NþFJþKHDIþ6N™þGKþLþ6Nþ	GþNNþKþNþ2HþELþN3EHEþKþMþN5KLGþNþMþN6LNNþ	6þNIþIþNþJIþHþLþ3þGþNDþ3þ43IþFþNLþEþH5OþH2þLDþH6þ_HþGDþINþKIþNKþIOMþJNNþHHMþNþHþNþNþNDþJDþKKþLþMþMþMÿþIþKMþ	IJþEþKKHEþJOIHLKþHþDIþJKLþNþFHFG6HþENN3þJNIK¨_KINGþNLFHFHKLþHHNNNþFLNMEšOþFþ2HþNþ22IþHIG12MNEFHEFJ6NþGNþH_þ264HþMMLNNþKþ­NNþGM1þIKþ6NþJGNþ®NLD2þHþNJþ6N™þ2ENþNGD2GþJþ6NþIKþNNKHþKþNNþNMþNNþLþNþ2HþLLþ®þNNþMþN3EHEþLþ®þNþM1þMþN5KLGKþMþILþND2¨FHLþMþN6LNNNþMþ65þND2GFLLLþNIþI5þKHþJ2þLLþNþJIIJþ_DþLþHþLKLþKþLþ3þGþþLþHJþ	3þ43IþFþþEEþ	Eþ4H5OþH2þ¯þEEEþ5H6þ_HþMþLL32þ
LINþKIþMþLLþEDþIOMþJNþLþ_KþHHMþJþOþHþKþNþNþLþHNþMþMþMÿþFþJþFJþ6GFþKHFHþI1I22þEEJFþMJFþH46þFJKOIþGHHFþN6þHKFMMJEIþ™N6þDþKDþN6þHþGLþNNþGILþHþH2þNþKþMþKþEHE3NþIDGMCþNþGLK5Nþ6HþNNL6NþIJþ
INþIJDþNþLþHþDNþGþ3þLNþFþI34þ3þDLþ2HþO5HþEþDGþH_þ6HþKNþIKþNIþNNJþMOIþNþMHHþNþHþDNþNþDJþKKþLþMþMþMÿ