þ97þ;::7þ;::8þ;::&þ;8($þ766$($þ98þ766$##&('þ;;:8þ76664#9;<::(þ;;:8þ7666439;þ;::6þ;;85666439;þ;::6þ;:75339;þ	;895þ;:98þ766793þ;;:8þ7&%%$%9:6þ;;:7þ7''&#%9;<::7þ;;:6þ7666'&9;þ;:97þ;;9566&4%';þ;:96þ;;84339;þ	;895þ;:95;þ
766794þ;;:7þ7666439:7þ;;:(þ766&439;;:9þ;;)(þ76&&%$9;þ;:þ;**&&66439;þ;þ+;(#339;þ;*'#;þ
7þ;)*'þ766þ*+*8þ766&%þ;;:7þ766&%$9þ;;:5666439;þ;:95339;þ;:95;þ;;:ÿþ::6þ;895þ766793þ7&%%$%9:6þ''&#%9;<::7þ6'&9;þ;:97þ%';þ;:96þ;þ	;895þ766794þ7666439:7þ766&439;;:96þ(þ76&&%$9;þ;:86þ*&&66439;þ;)75þ;(#339;þ	;('5þ;*'#;þ
76&%'3þ;)*'þ766&$%9*6þ*+*8þ766&%$9;;:)7þ;;:7þ766&%$9;þ;:)'þ;;:5666439;þ;:(&þ;:95339;þ	;8'$þ;:95;þ
7667'$þ;;:8þ766643)(&þ;;*(þ766&439;;:)6þ;+*'þ'6&&%&9;þ;:)7þ;*)%%%$#$9;þ;:99þ+;)%'%';þ	99þ;:(6;þ;)98þ*;:8þ;;:8þ;;;9þ;:ÿþ79þ7::;þ8::;þ&::;þ$(8;þ$($667þ'(&##$667þ89þ(::<;9#46667þ8:;;þ
6::;þ;9346667þ8:;;þ
6::;þ;93466658;;þ
598;þ	;93357:;þ
397667þ89:;þ
6:9%$%%&7þ8:;;þ
7::<;9%#&''7þ7:;;þ
79:;þ;9&'6667þ6:;;þ
69:;þ;'%4&6659;;þ
598;þ	;93348;;þ
497667þ
;59:;þ
7:9346667þ7:;;þ9:;;934&667þ(:;;þ:;þ;9$%&&67þ();;þ;þ;93466&&**;þ;933#(;+þ7þ
;#'*;þ667þ'*);þ%&667þ8*+*þ9$%&667þ7:;;þ;9346665:;;þ;93359:;þ;59:;þ:;;ÿþ6::þ598;þ397667þ6:9%$%%&7þ7::<;9%#&''þ79:;þ;9&'6þ69:;þ;'%þ598;þ	;þ497667þ7:9346667þ69:;;934&667þ68:;þ;9$%&&67þ(þ57);þ;93466&&*þ5'(;þ	;933#(;þ3'%&67þ
;#'*;þ
6*9%$&667þ'*);þ
7):;;9$%&667þ8*+*þ
'):;þ;9$%&667þ7:;;þ
&(:;þ;9346665:;;þ
$'8;þ	;93359:;þ
$'7667þ
;59:;þ
&()346667þ8:;;þ
6):;;934&667þ(*;;þ
7):;þ;9&%&&6'þ'*+;þ
99:;þ;9$#$%%%)*;þ99þ	;'%'%);+þ;6(:;þ89);þ8:;*þ8:;;þ9;;;þ:;ÿþppppþppppppppþppppppppppppþppppppppppppppppþppppppppppppppppppppþ
ppppppppppppppppppppppppþppppppppppppppppppppppppppppþppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppþppppppppppppppppppppppppppppþppppppppppppppppppppppppþ
ppppppppppppppppppppþppppppppppppppppþppppppppppppþppppppppþppppÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEhEhEÇEÄÄþÃÃDÇChCgCgChEÇÄÄþÃÃÇDhDgDfDfDgDhEÇDÄÄþ
ÃÃCÇEhCgDfDeDeDfCgDhCÇÄÄþÃÃÇChFgFfCeBdBdBeBfDgChFÇEÄÄþÄÄCÇFhEgFfDeCdCcCcCdDeCfFgEhEÇÄÄÅÅÂÂgEfEeEdEcBbBbBcBdDeCfFgCÃÃÇÇþÅÅÂÂFgEfEeEdEcBcBdBeDfCgÃÃÇÇþÅÅÂÂgEfDeEdEdEeEfCgDÃÃÇÇþ
ÅÅÂÂEgFfEeDeDfDgÃÃÇÇþÅÅÂÂgDfDfDgDÃÃÇÇþÅÅÂÂFgFgÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEhEhEÇEÄÄþÃÃDÇChCgCgChEÇÄÄþÃÃÇDhDgDfDfDgDhEÇDÄÄþ
ÃÃCÇEhCgDfDeDeDfCgDhCÇÄÄþÃÃÇChFgFfCeBdBdBeBfDgChFÇEÄÄþÄÄCÇFhEgFfDeCdCcCcCdDeCfFgEhEÇÄÄÅÅÂÂgEfEeEdEcBbBbBcBdDeCfFgCÃÃÇÇþÅÅÂÂFgEfEeEdEcBcBdBeDfCgÃÃÇÇþÅÅÂÂgEfDeEdEdEeEfCgDÃÃÇÇþ
ÅÅÂÂEgFfEeDeDfDgÃÃÇÇþÅÅÂÂgDfDfDgDÃÃÇÇþÅÅÂÂFgFgÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEhEhEÇEÄÄþÃÃDÇChCgCgChEÇÄÄþÃÃÇDhDgDfDfDgDhEÇDÄÄþ
ÃÃCÇEhCgDfDeDeDfCgDhCÇÄÄþÃÃÇChFgFfCeBdBdBeBfDgChFÇEÄÄþÄÄCÇFhEgFfDeCdCcCcCdDeCfFgEhEÇÄÄÅÅÂÂgEfEeEdEcBbBbBcBdDeCfFgCÃÃÇÇþÅÅÂÂFgEfEeEdEcBcBdBeDfCgÃÃÇÇþÅÅÂÂgEfDeEdEdEeEfCgDÃÃÇÇþ
ÅÅÂÂEgFfEeDeDfDgÃÃÇÇþÅÅÂÂgDfDfDgDÃÃÇÇþÅÅÂÂFgFgÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEhEhEÇEÄÄþÃÃDÇChCgCgChEÇÄÄþÃÃÇDhDgDfDfDgDhEÇDÄÄþ
ÃÃCÇEhCgDfDeDeDfCgDhCÇÄÄþÃÃÇChFgFfCeBdBdBeBfDgChFÇEÄÄþÄÄCÇFhEgFfDeCdCcCcCdDeCfFgEhEÇÄÄÅÅÂÂgEfEeEdEcBbBbBcBdDeCfFgCÃÃÇÇþÅÅÂÂFgEfEeEdEcBcBdBeDfCgÃÃÇÇþÅÅÂÂgEfDeEdEdEeEfCgDÃÃÇÇþ
ÅÅÂÂEgFfEeDeDfDgÃÃÇÇþÅÅÂÂgDfDfDgDÃÃÇÇþÅÅÂÂFgFgÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEjEjEÇEÄÄþÃÃDÇCjCiCiCjEÇÄÄþÃÃÇDjDiDhDhDiDjEÇDÄÄþ
ÃÃCÇEjCiDhDgDgDhCiDjCÇÄÄþÃÃÇCjFiFhCgBfBfBgBhDiCjFÇEÄÄþÄÄCÇFjEiFhDgCfCeCeCfDgChFiEjEÇÄÄÅÅÂÂiEhEgEfEeBdBdBeBfDgChFiCÃÃÇÇþÅÅÂÂFiEhEgEfEeBeBfBgDhCiÃÃÇÇþÅÅÂÂiEhDgEfEfEgEhCiDÃÃÇÇþ
ÅÅÂÂEiFhEgDgDhDiÃÃÇÇþÅÅÂÂiDhDhDiDÃÃÇÇþÅÅÂÂFiFiÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEjEjEÇEÄÄþÃÃDÇCjCiCiCjEÇÄÄþÃÃÇDjDiDhDhDiDjEÇDÄÄþ
ÃÃCÇEjCiDhDgDgDhCiDjCÇÄÄþÃÃÇCjFiFhCgBfBfBgBhDiCjFÇEÄÄþÄÄCÇFjEiFhDgCfCeCeCfDgChFiEjEÇÄÄÅÅÂÂiEhEgEfEeBdBdBeBfDgChFiCÃÃÇÇþÅÅÂÂFiEhEgEfEeBeBfBgDhCiÃÃÇÇþÅÅÂÂiEhDgEfEfEgEhCiDÃÃÇÇþ
ÅÅÂÂEiFhEgDgDhDiÃÃÇÇþÅÅÂÂiDhDhDiDÃÃÇÇþÅÅÂÂFiFiÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEjEjEÇEÄÄþÃÃDÇCjCiCiCjEÇÄÄþÃÃÇDjDiDhDhDiDjEÇDÄÄþ
ÃÃCÇEjCiDhDgDgDhCiDjCÇÄÄþÃÃÇCjFiFhCgBfBfBgBhDiCjFÇEÄÄþÄÄCÇFjEiFhDgCfCeCeCfDgChFiEjEÇÄÄÅÅÂÂiEhEgEfEeBdBdBeBfDgChFiCÃÃÇÇþÅÅÂÂFiEhEgEfEeBeBfBgDhCiÃÃÇÇþÅÅÂÂiEhDgEfEfEgEhCiDÃÃÇÇþ
ÅÅÂÂEiFhEgDgDhDiÃÃÇÇþÅÅÂÂiDhDhDiDÃÃÇÇþÅÅÂÂFiFiÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿþÃÃÃÃþÃÃEÇEÇÄÄþÃÃÇEjEjEÇEÄÄþÃÃDÇCjCiCiCjEÇÄÄþÃÃÇDjDiDhDhDiDjEÇDÄÄþ
ÃÃCÇEjCiDhDgDgDhCiDjCÇÄÄþÃÃÇCjFiFhCgBfBfBgBhDiCjFÇEÄÄþÄÄCÇFjEiFhDgCfCeCeCfDgChFiEjEÇÄÄÅÅÂÂiEhEgEfEeBdBdBeBfDgChFiCÃÃÇÇþÅÅÂÂFiEhEgEfEeBeBfBgDhCiÃÃÇÇþÅÅÂÂiEhDgEfEfEgEhCiDÃÃÇÇþ
ÅÅÂÂEiFhEgDgDhDiÃÃÇÇþÅÅÂÂiDhDhDiDÃÃÇÇþÅÅÂÂFiFiÃÃÇÇþÅÅÂÂÃÃÇÇþÅÅÇÇÿ